### ISSUE TITLE
Default IP Address should be 127.0.0.1 instead of 0.0.0.0

### ISSUE THREAD

**Issue by notthetup** [indexzero/http-server#128]
Based on [RFC 5735](http://tools.ietf.org/html/rfc5735), 0.0.0.0 is non-routable. 

Recently [Chrome stopped routing it to 'localhost' and searching the string "0.0.0.0" on Google instead](https://code.google.com/p/chromium/issues/detail?id=428046).

127.0.0.1 is a more safe solution for the default address.

**Comment by notthetup** [comment]
I should clarify, that there is no technical issue here. Just that if someone copies and pastes the IP address from the command line output : 

`Starting up http-server, serving ./ on: http://0.0.0.0:8080`

Chrome will try to search the string "0.0.0.0:8000" instead of loading the localhost website.

**Comment by 1j01** [comment]
`http-server -o` completely fails because of this

**Comment by taneltm** [comment]
0.0.0.0 binds to all IPv4 interfaces, while 127.0.0.1 is only localhost.

I think binding to 0.0.0.0 by default is better as this tool is "zero-configuration".

If the -o switch is used without the -a switch, browser should open http://127.0.0.1

**Comment by 1j01** [comment]
@taneltm Yeah, that's what I was thinking. Except maybe http://localhost instead. Does 127.0.0.1 have better support than localhost? It's at least highlighted here as a URL where http://localhost is not :P

**Comment by taneltm** [comment]
Localhost is set by the hosts file, at least on windows.
You can have localhost pointing to an ip address which is not 127.0.0.1, so http://127.0.0.1 would be better, imo.

**Comment by indexzero** [comment]
Fixed in #132.
