### ISSUE TITLE
proxy feature doesn't work when http-server is installed through npm

### ISSUE THREAD

**Issue by shepeliev** [indexzero/http-server#136]
root@4aea958c1cb6:/# npm install http-server -g
/usr/bin/http-server -> /usr/lib/node_modules/http-server/bin/http-server
/usr/bin/hs -> /usr/lib/node_modules/http-server/bin/http-server
http-server@0.7.5 /usr/lib/node_modules/http-server
├── opener@1.4.0
├── colors@1.0.3
├── union@0.4.4 (qs@2.3.3)
├── portfinder@0.2.1 (mkdirp@0.0.7)
├── optimist@0.6.1 (wordwrap@0.0.2, minimist@0.0.10)
└── ecstatic@0.6.1 (mime@1.3.4, minimist@1.1.1, he@0.5.0)
root@4aea958c1cb6:/# http-server -h
usage: http-server [path] [options]

options:
  -p                 Port to use [8080]
  -a                 Address to use [0.0.0.0]
  -d                 Show directory listings [true]
  -i                 Display autoIndex [true]
  -e --ext           Default file extension if none supplied [none]
  -s --silent        Suppress log messages from output
  --cors             Enable CORS via the 'Access-Control-Allow-Origin' header
  -o                 Open browser window after staring the server
  -c                 Cache time (max-age) in seconds [3600], e.g. -c10 for 10 seconds.
                     To disable caching, use -c-1.

  -S --ssl           Enable https.
  -C --cert          Path to ssl cert file (default: cert.pem).
  -K --key           Path to ssl key file (default: key.pem).

  -h --help          Print this list and exit.
root@4aea958c1cb6:/#

**Comment by jantimon** [comment]
There hasn't been a new release since the proxy feature was merged

**Comment by indexzero** [comment]
Will be released in `0.8.0` shortly.
