### ISSUE TITLE
No support for environment variables

### ISSUE THREAD

**Issue by visualjeff** [indexzero/http-server#140]
My app running in http-server need an environment variable and it looks as if environment variables aren't available to the running application.

**Comment by EskelCz** [comment]
@visualjeff how did you solve this?

**Comment by zbynek** [comment]
> My app running in http-server

`http-server` only serves static files, so I'm not sure what do you mean by this.

**Comment by EskelCz** [comment]
@zbynek I need a way to inject environment specific information, for front-end configuration. Not sure how to go about it technically.

**Comment by zbynek** [comment]
@EskelCz I think the best option is to dump the environment variables into some computer readable file (e.g. `env.js`) before you start `http-server`, then include `env.js` in all your html files that need it (or load it via js). This should be possible with some bash script along the lines of
```
echo "env = {};" > env.js; env | sed 's/\([^=]*\)=\(.*\)/env.\1="\2";/' >> env.js
```

**Comment by EskelCz** [comment]
@zbynek that’s perfect, thanks a lot
