### ISSUE TITLE
Support no-store header

### ISSUE THREAD

**Issue by sunshineo** [indexzero/http-server#143]
Correct me if I'm wrong. Even with no-cache, or max-age=-1 , the browser actually saves a copy. And next time it needs to use the copy, it send an conditional request to server. And if it not modified, server will return a 304 without the content of the file and browser happily use the local copy.

The no-store header however will force the browser to make a request every time it wants to use the file and get the content and get a 200.

This is a feature request I guess.

**Comment by NekR** [comment]
@sunshineo just use `-c no-store`. `http-server` uses `node-ecstatic` which says that if `cache` field isn't number, then it's passed to `Cache-Control` as is. So you can actually put whatever string you want there.

**Comment by thornjad** [comment]
@sunshineo I believe that solution should work. Please re-open if not!
