### ISSUE TITLE
Access-Control-Request-Headers:range

### ISSUE THREAD

**Issue by dahang** [indexzero/http-server#145]
Request header field Range is not allowed by Access-Control-Allow-Headers.
can you add this 
this.headers['Access-Control-Allow-Headers'] = 'Origin, X-Requested-With, Content-Type, Accept ,range';

to support 206 Partial Content

**Comment by MurWade** [comment]
ya this would be nice. whats the process on this?

**Comment by danielweck** [comment]
Related: https://github.com/indexzero/http-server/issues/154
(summary of proposal: remove the arbitrary headers override)

**Comment by indexzero** [comment]
Fixed in #157
