### ISSUE TITLE
Serving files from directories with spaces in name returns 404

### ISSUE THREAD

**Issue by VilleSalonen** [indexzero/http-server#146]
If served directory contains subdirectories with spaces in names, their listings can be read but if I attempt to read a file from such a subdirectory, I get 404.

**Comment by VilleSalonen** [comment]
Based on my preliminary investigation, spaces are incorrectly escaped when file is read from subdirectory with spaces.

    When requesting a file: /file%20with%20spaces
    When requesting a subdirectory listing: /directory%20with%20spaces/
    When requesting a file from a subdirectory: /directory%2520with%2520spaces/file

**Comment by VilleSalonen** [comment]
Based on further investigation the problem is with directory listings. Directory listings contain links with incorrect escapes. If I access the file with URL /directory%20with%20spaces/file, I can download it just fine.

**Comment by VilleSalonen** [comment]
The bug is actually in ecstatic. I made a pull request which fixes this problem: https://github.com/jfhbrook/node-ecstatic/pull/138

**Comment by ralake** [comment]
This is the same problem I explained (in a much poorer way) in #144.

**Comment by thornjad** [comment]
Fixed in ecstatic
