### ISSUE TITLE
still preferGlobal?

### ISSUE THREAD

**Issue by jasonkarns** [indexzero/http-server#151]
I'd like to gauge how http-server is actually being used by most folks. http-server currently prefers global installs. I'm not convinced this should be the case.

Rather than prematurely trying to outline my rationale for no longer preferring global install; I think it would be more productive to just poll for current use of http-server. My hunch is that a surprising number of users have http-server listed as a package dependency (likely devDependency), and as such, http-server is installed locally thus negating any reason to `preferGlobal`.

So, who uses http-server primarily as a global package (ie, it's *not* listed in your apps' package.json) and who primarily has http-server listed as a package.json dependency or devDependency?

poll: http://strawpoll.me/4285850

**Comment by indexzero** [comment]
@jasonkarns a poll probably isn't the best way to figure this out. You could probably just check the dependencies in `npm`, which right now only has 38 dependent packages.: https://www.npmjs.com/package/http-server

**Comment by jasonkarns** [comment]
that only accounts for libraries. (and public libraries at that). My hypothesis is that a significant percentage of users do indeed depend on http-server in package.json (primarily apps which wouldn't be on npm)

**Comment by indexzero** [comment]
@jasonkarns ok. Let me know how that pans out!
