### ISSUE TITLE
HTTP headers overwrite user config, just before CORS preflight

### ISSUE THREAD

**Issue by danielweck** [indexzero/http-server#154]
https://github.com/indexzero/http-server/blob/master/lib/http-server.js#L46

```javascript
if (options.cors) {
    this.headers['Access-Control-Allow-Origin'] = '*';
    this.headers['Access-Control-Allow-Headers'] = 'Origin, X-Requested-With, Content-Type, Accept';

    before.push(corser.create());
}
```

For example, in our app we need the `Range` header in `Access-Control-Allow-Headers`, but the above code overwrites our command line / JSON configuration.

Suggested fix: remove the predefined HTTP headers, which should be at the discretion of client-side usage, not baked / hard-coded as default values:

```javascript
    this.headers['Access-Control-Allow-Origin'] = '*';
    this.headers['Access-Control-Allow-Headers'] = 'Origin, X-Requested-With, Content-Type, Accept';
```

**Comment by danielweck** [comment]
Related: https://github.com/indexzero/http-server/issues/145

**Comment by StyMaar** [comment]
I'm not sure I understand your proposal. 
“Suggested fix: remove the predefined HTTP headers, which should be at the discretion of client-side usage, not baked / hard-coded as default values:”
Do you want to replace the `--cors` option by user set `'Access-Control-Allow-Headers` ? 
What “JSON configuration are you talking about ” ?

**Comment by StyMaar** [comment]
Oh, maybe you're referring to this pull request ? https://github.com/indexzero/http-server/pull/64

**Comment by danielweck** [comment]
Both `Access-Control-Allow-Origin` and `Access-Control-Allow-Headers` should be totally configurable on the client side of the HTTP-Server API. I am not against sensible defaults, but the current implementation does not even allow us ; i.e. users of the HTTP-Server library / utility ; to alter (remove, add) these predefined headers, which are forced to arbitrary values despite the passed user-defined `options.headers`:

https://github.com/indexzero/http-server/blob/master/lib/http-server.js#L24
```javascript
 this.headers = options.headers || {};
```

https://github.com/indexzero/http-server/blob/master/lib/http-server.js#L46
```javascript
if (options.cors) {
    this.headers['Access-Control-Allow-Origin'] = '*';
    this.headers['Access-Control-Allow-Headers'] = 'Origin, X-Requested-With, Content-Type, Accept';

    before.push(corser.create());
  }
```

**Comment by danielweck** [comment]
I made a note about the recent fix for the `range` header: https://github.com/indexzero/http-server/pull/157/files#diff-836f2aa6eaa69f58c19a701c784dbf24R48

**Comment by danielweck** [comment]
I would love to publish a Pull Request for this, but unfortunately I have no free cycles at the moment.

Our fork simply hard-codes the header values, just as you do (we did not implement any architectural improvements).

Ideally, `bin/http-server` would consume header values specified in `argv` command line parameters (e.g. `http-server --header NAME1 VALUE1 --header NAME2 VALUE2`), pass them over to `var server = httpServer.createServer(options)` via the `options` function parameter, and `lib/http-server.js` would take into account existing values in `this.headers[]` (instead of completely overwriting existing values).

For example, `Access-Control-Allow-Origin` is currently forced to `*`, making it impossible to opt for another origin URL (other than by forking your code, and hard-coding new values).

**Comment by nickdesaulniers** [comment]
Hey @danielweck , I'm curious, is it ever the case that you want certain headers allowed but certain headers not allowed?  I'm curious as to the use case for not having a single whitelist.

**Comment by danielweck** [comment]
@nickdesaulniers I am just referring to the fact that as a user of http-server, I cannot configure my own HTTP CORS header *values* because of those that are hard-coded in the `if (options.cors)` code block.

**Comment by danielweck** [comment]
I'm happy with being able to add CORS headers to the predefined list:
https://github.com/indexzero/http-server/pull/150
Thanks!
