### ISSUE TITLE
Support for Live Reload

### ISSUE THREAD

**Issue by tusharmath** [indexzero/http-server#163]
Live Reload makes a lot of sense when in development mode.

**Comment by jdmaurer** [comment]
+1

**Comment by derhuerst** [comment]
I don't think live reload is suited to this module, since *http-server* is on purpose very lightweight.

**Comment by indexzero** [comment]
Will see what folks think on this before considering it. How many +1s will it get?

**Comment by ericdouglas** [comment]
+1

**Comment by shairez** [comment]
+1

**Comment by gelevanog** [comment]
+1

**Comment by derhuerst** [comment]
Please use the [reaction feature](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments) to show your support for this issue.

**Comment by rockie-yang** [comment]
find this command, 

    nodemon `which http-server`
