### ISSUE TITLE
Emulate modem speeds

### ISSUE THREAD

**Issue by tusharmath** [indexzero/http-server#164]
There should be a way to emulate modem speed.

**Comment by taneltm** [comment]
The connection is usually slow on the client side, so it would make more sense to slow down the browser instead.
Chrome dev tools has connection speed throttling built in. I use it quite often for emulating slower mobile connections like GPRS and 2G.

**Comment by tusharmath** [comment]
I am using [this](https://github.com/tusharmath/multi-threaded-downloader) module to test file downlaod. The problem is that the download happens so fast that I am unable to test. The same applies to `curl`  requests.

**Comment by taneltm** [comment]
I still think it is something that you should not include into the server itself.
Have you tried to throttle the speed with a proxy? - This seems simple enough... https://github.com/mistakster/throttle-proxy/

**Comment by tusharmath** [comment]
I guess you are right. I will try that module.

On Thu, Jul 2, 2015, 11:58 AM Tanel <notifications@github.com> wrote:

> I still think it is something that you should not include into the server
> itself.
> Have you tried to throttle the speed with a proxy? - This seems simple
> enough... https://github.com/mistakster/throttle-proxy/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/indexzero/http-server/issues/164#issuecomment-117923410>
> .
>
-- 
Regards,
Tushar Mathur.
www.tusharm.com

**Comment by indexzero** [comment]
Duplicate of #110
