### ISSUE TITLE
Why I can't use ajax request with the post method when I run http-server?

### ISSUE THREAD

**Issue by zhangbg** [indexzero/http-server#172]
Why I can't use ajax request with the post method when I run http-server? Any help will be appreciated!

**Comment by stv8** [comment]
+1

**Comment by derhuerst** [comment]
Just gessing: This is a simple read-only HTTP server and `POST` is by definition a method that stores something on the server.

**Comment by stv8** [comment]
@derhuerst yeah after looking through the code I noticed there was no logic for `POST` thanks!

**Comment by fringd** [comment]
no logic for GET either. I have a use case where I need the server to respond to post with the file, just ignoring any post body and responding the same as you would for a GET.

+1

**Comment by derhuerst** [comment]
@fringd HTTP `GET` works just fine. `http-server` serves all files in the selected directory.

`POST` by definition creates new resources/files and will fail if you do it twice. This server does not support uploading.

**Comment by sushruth** [comment]
Can we have an option to pass POST through as a GET ?

**Comment by derhuerst** [comment]
> Can we have an option to pass POST through as a GET ?

This is actually against all web best practices. It conflicts with the HTTP spec. I'm not the maintainer of this module, but **I'd strongly suggest you to revisit your solution/requirements**, rather than putting this unsemantical (and quite narrow) feature into `http-server`.
