### ISSUE TITLE
Error: connect ETIMEDOUT 127.0.0.1:8060

### ISSUE THREAD

**Issue by alejandroiglesias** [indexzero/http-server#185]
I usually leave this server running for development and once in a while, specially every morning when resuming my laptop to keep working, I get this `ETIMEDOUT` error. I'm using version `0.8.5`. Any clues about it?

```
/usr/local/lib/node_modules/http-server/node_modules/http-proxy/lib/http-proxy/index.js:119
    throw err;
    ^

Error: connect ETIMEDOUT 127.0.0.1:8060
    at Object.exports._errnoException (util.js:837:11)
    at exports._exceptionWithHostPort (util.js:860:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1060:14)
```

**Comment by thornjad** [comment]
This could be happening if a request is made to the server just before the laptop sleeps/hibernates/whatever, and so the response is never sent? Do you still see this issue on the latest version of `http-server`?

**Comment by alejandroiglesias** [comment]
I don't know about this anymore since I'm using `http-proxy` now.
