### ISSUE TITLE
How do I run http-server in the background

### ISSUE THREAD

**Issue by globexdesigns** [indexzero/http-server#189]
Running:

```
http-server . &
```

Doesn't seem to work. It also doesn't play nice with `forever` or `supervisor`.

Any other suggestions?

**Comment by derhuerst** [comment]
For me, `http-server . &` works. I just have to press enter once more to get my prompt back. :P

I'm having trouble installing forever right now, but i will let you know if it works for me.

**Comment by derhuerst** [comment]
`forever start $(which http-server) .` works as well for me.

**Comment by indexzero** [comment]
That or 

```
forever start -c http-server
```

**Comment by ksloan** [comment]
```
http-server . > http.log 2>&1 &
```

**Comment by deepakppatil** [comment]
http-server . > http.log 2>&1 &
echo $! > /var/tmp/pidfile
pkill --pidfile /var/tmp/pidfile

**Comment by andradedpg** [comment]
@jackdh 

See PID with 

`$ netstat -nlp`

After KILL pid

`$ kill 999`

**Comment by pengliheng** [comment]
@jackdh kill the process

**Comment by simonsmith** [comment]
For those still stuck from Google:

https://stackoverflow.com/questions/47881223/running-http-server-in-background-from-an-npm-script

`npm-run-all` with `--race` works best

**Comment by luckydevboy** [comment]
`nohup http-server . &`
