### ISSUE TITLE
urls in log incomplete?

### ISSUE THREAD

**Issue by vectorsize** [indexzero/http-server#195]
shouldn't the addresses in [line 122](https://github.com/indexzero/http-server/blob/master/bin/http-server#L122) rather be like this?

`protocol      = ssl ? 'https://' : 'http://';`

rather than

`protocol      = ssl ? 'https:' : 'http:';`

I know it's just debuging but if the urls are "correct" then on osx terminal you can click on them to open them in the browser directly ^^

or maybe I'm missing something?

thanks!

**Comment by jcpst** [comment]
Came here to say the same exact thing. 

In xfce-terminal if the link is valid, then you can click on them to open, "copy as url", etc. I was doing this quite a bit until I updated http-sever.

**Comment by thornjad** [comment]
Fixed in #220
