### ISSUE TITLE
 methods post, remove???

### ISSUE THREAD

**Issue by PrDmiter** [indexzero/http-server#196]
I'm a beginner, please help me)
How to fix it - POST http://localhost:8000/clients/clients.json 405 (Method Not Allowed)?
With GET all good.

**Comment by riceboyler** [comment]
@PrDmiter This is a simple/basic read-only server. It doesn't support POST methods (there's no logic to handle it).

**Comment by PrDmiter** [comment]
Thank! I realized this, so express studied and wrote it himself.

**Comment by andreieftimie** [comment]
Would it be a good idea to pass on POST (and other request types) if there is a ```proxy``` set up?

**Comment by sushruth** [comment]
I agree with @andreieftimie. Helps us with mock data. I think it does not need to do much to pass through either.

**Comment by helloint** [comment]
sadly no response over the past years.
