### ISSUE TITLE
Support for fallback option

### ISSUE THREAD

**Issue by juergenzimmermann** [indexzero/http-server#198]
For SPAs it would be good to have an option like `--fallback '/my/path/index.html'`.
The option's value would be the file to serve when a route is not found.
The default value could be source folder + /index.html.

**Comment by riceboyler** [comment]
+1 for this suggestion. I recognize that http-server is not really intended to handle routes, but a "default route" would be really nice.

**Comment by thornjad** [comment]
Putting a `404.html` file into the source directory achieves the desired result (see https://github.com/indexzero/http-server/pull/369#issuecomment-386940370). Check out the discussion in #369.
