### ISSUE TITLE
How to disable directory listings?

### ISSUE THREAD

**Issue by sapegin** [indexzero/http-server#200]
Readme just says how to enable it but it’s already enabled by default.

**Comment by frjalex** [comment]
Same question here

**Comment by frjalex** [comment]
the 'False' param just wont work

**Comment by sebgymn** [comment]
`-d false`

**Comment by lunyx** [comment]
I'm having this same issue as well.  

Running: http-server /www -d False -i False -p 80

The directory listing still shows up.

**Comment by kamakazikamikaze** [comment]
This issue can be closed.

@bekce Submitted the correct answer. The reason why your directory listings still show is because of capitalization: `False` is a string, `false` is a boolean

**Comment by lunyx** [comment]
That explains a lot... The readme has `-d Show directory listings (defaults to 'True')`, which implied to me that `False` should've also started capitalized.

**Comment by kamakazikamikaze** [comment]
I didn't think to change the capitalization until I invoked `-h` in the CLI which displays it as lowercase. At the moment I was actually working on reading in JSONs in Python where the capitalization is also different (`true` --> `True`), so it suddenly made sense.

One of those "subtle but significant" factors that make a world of difference when auto-casting variable types...

**Comment by frjalex** [comment]
I think it's not an urgent issue, as it's always far more convenient to use the server as a nodejs module but not as-an application.

**Comment by killroy42** [comment]
Did this change recently? I've been using http-server for a long time as a quick way to point port 80 at my various test servers. Suddenly I got listings which I never got before. Took me a while to find this thread... PS: on the command line everything is a string. It might make more sense to either accept all capitalizations, or to output an error for an "invalid value for d", for example.

**Comment by BigBlueHat** [comment]
Closing in favor of #450. I'll also update the README (as it uses init-caps...confusingly).

**Comment by BigBlueHat** [comment]
See 94329688b5bf6c058a9f2c24739bd628b7345dce
