### ISSUE TITLE
-bash: http-server: command not found

### ISSUE THREAD

**Issue by martianmartian** [indexzero/http-server#204]
I'm on Mac terminal trying to serve a file. it gave this error. can someone help?

**Comment by derhuerst** [comment]
How did you install it? I'm assuming you installed *http-server* with `npm install -g http-server`.

What does `which http-server` give you?

**Comment by indexzero** [comment]
This is not enough information to debug the issue. Could you please provide:

- Full command you are trying to run
- Your `http-server`, `node` and `npm` version.
- Full output you are seeing.
