### ISSUE TITLE
Generate random port number

### ISSUE THREAD

**Issue by Zianwar** [indexzero/http-server#210]
Hello, I'd really want that each time I execute 
```
$http-server
``` 
would give a different port

**Comment by derhuerst** [comment]
If you want to run `http-server` (with a random number) *in a script*, you can do the following.

```shell
port=$(node -e "process.stdout.write(''+(1000+Math.round(Math.random()*9000)))")
http-server -p $port
```

If you want to run `http-server` (with a random number) *from the command line*, you can set an alias for generating a random port. In your `.bashrc`/`.zshrc`, do the following.

```shell
alias rport=node -e "process.stdout.write(''+(1000+Math.round(Math.random()*9000)))"
```

Then you can call it from the command line with `http-server $(rport)`.

**Comment by Zianwar** [comment]
Thank you @derhuerst !
