### ISSUE TITLE
Using HTTP-Server together with Nexe and Browser-Sync

### ISSUE THREAD

**Issue by MartinMuzatko** [indexzero/http-server#212]
Hello there!

Being very new to node, I wonder if I could use HTTP-Server programatically as node app (node server.js) with manual require and createServer()

Unfortunately, that doesn't work, is there a way to start the server as node app?
https://github.com/jaredallard/nexe Nexe works together with apps that run as node apps.

Additionally, I want to use Browser-Sync with http-server if that is possible. For that I need to run the server as node app too. (see https://github.com/Browsersync/recipes/tree/master/recipes/server )

Thank you in advance.

**Comment by derhuerst** [comment]
Not sure if I understood, but `http-server` is built in on top of [`ecstatic`](https://www.npmjs.com/ecstatic), which [supports scripted usage](https://github.com/jfhbrook/node-ecstatic#stock-http-server).

**Comment by MartinMuzatko** [comment]
Thank you a lot @derhuerst.

So, if I understand that right, http-server is just an executable, that is not meant for node app usage? so there is no package that I can require and run?

Again: thank you a lot for clearing that up.

**Comment by derhuerst** [comment]
[The `package.json` specifies which file will be `require`d if you `require` `http-server`.](package.json#L5)

[The executables are defined in the `package.json` as well.](package.json#L80-L83)

**Comment by derhuerst** [comment]
For usage in Node.js you could use [`ecstatic`](https://www.npmjs.com/package/ecstatic), [`express`](https://www.npmjs.com/package/express), [`hapi`](https://www.npmjs.com/package/hapi) or the [builtin `http` module](https://nodejs.org/api/http.html#http_http_createserver_requestlistener).

**Comment by MartinMuzatko** [comment]
Thanks a lot @derhuerst  This is a great starting point :)
