### ISSUE TITLE
Symbolic links can cause incorrect response headers

### ISSUE THREAD

**Issue by battlesnake** [indexzero/http-server#213]
# To reproduce

```
echo '<!doctype html><html><head><meta charset="utf-8"><title>Test</title></head><body>Hello world</body></html>' > test.html
ln -s test.html test
http-server
```

Then go to http://localhost:8080/test
# Expected behaviour

Server resolves target (realpath?) then prepares HTTP response based on target file

```
Content-Type: text/html
```
# Observed behaviour

Server does not resolve target, causing incorrect HTTP response

```
Content-Type: application/octet-stream; charset=utf-8
```

**Comment by thornjad** [comment]
This is an issue in `node-ecstatic`, not `http-server`, see discussion in jfhbrook/node-ecstatic#168
