### ISSUE TITLE
EADDRINUSE instead of finding a free port

### ISSUE THREAD

**Issue by thorn0** [indexzero/http-server#215]
As per #18, if the default port 8080 is in use, some other free port should automatically get found and used. However, this doesn't happen (Node 5.1, Windows 7 x64).

```
d:\foo>http-server
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 0.0.0.0:8080
    at Object.exports._errnoException (util.js:856:11)
    at exports._exceptionWithHostPort (util.js:879:20)
    at Server._listen2 (net.js:1234:14)
    at listen (net.js:1270:10)
    at net.js:1379:9
    at doNTCallback3 (node.js:463:9)
    at process._tickCallback (node.js:369:17)
    at Function.Module.runMain (module.js:459:11)
    at startup (node.js:138:18)
    at node.js:974:3
```

**Comment by kmgilbert100** [comment]
Works on node 0.10.41 ... Not working on node 4.2.2

**Comment by kmgilbert100** [comment]
Havn't checked any versions in between but looks like it can't find a port on 4.2.2 or greater

**Comment by lmx99** [comment]
you can refer to that url
http://superuser.com/questions/262942/whats-different-between-ctrlz-and-ctrlc-in-unix-command-line/262948#262948

**Comment by BigBlueHat** [comment]
This is fixed when using the default port via the `portfinder` upgrade in 989fa1c7f5727da92ac727f673a2d4b7a121124a. It does *not* handle fallbacks when using the `-p` option. There's a pending/possible option for that which is under discussion in #363.
