### ISSUE TITLE
Binding address option and log

### ISSUE THREAD

**Issue by netheril96** [indexzero/http-server#216]
<img width="256" alt="screen shot 2015-12-04 at 01 10 48" src="https://cloud.githubusercontent.com/assets/836839/11577907/0cd37680-9a5c-11e5-9c93-8b5665db1978.png">

The option `-a` seems not working according to the log. However, if I visit `http://127.0.0.1:8080` access is denied. So the log must be wrong.

**Comment by mauvm** [comment]
Idem dito.

**Comment by netheril96** [comment]
Not anymore.
