### ISSUE TITLE
Read process.env.PORT by default if no port is defined

### ISSUE THREAD

**Issue by h2non** [indexzero/http-server#217]
It's mostly helpful, especially in Heroku.

**Comment by h2non** [comment]
I've just checkout the code and it's actually supported. Closing!

**Comment by matthias-ccri** [comment]
Probably document this?

**Comment by thornjad** [comment]
@matthias-ccri I'd love to accept a PR documenting this!

**Comment by ts-web** [comment]
I will do my civic duty... :)

https://github.com/http-party/http-server/pull/658

* this is my personal account; I didn't realize it until now
