### ISSUE TITLE
Error loading files from parent directory

### ISSUE THREAD

**Issue by dKab** [indexzero/http-server#222]
It's not an issue (most likely) but I have to be sure.

I have directory tree similar to:
- project
  - bower_components
    - lib
      - lib.css
  - app
    - index.html

My http-server is running in `app` directory. If I try to include `lib.css` in my index.html I get 404 error. I suspect that it is normal behavior and http-server can't serve files from ancestor directories. Am I correct? Or is it something wrong with my setup and http-server is supposed to be able to serve such files

**Comment by derhuerst** [comment]
How do you include `lib.css`?

**Comment by derhuerst** [comment]
AFAIK, `ecstatic` (the lib underlying `http-server`), [blocks requests that leave the web root](https://github.com/jfhbrook/node-ecstatic/blob/e8ebf8f2285f1146013b456a901b37acb4527579/lib/ecstatic.js#L88-L90).

**Comment by dKab** [comment]
>How do you include lib.css?
 <link rel="stylesheet" href="../bower_components/lib/lib.css" /> why?

**Comment by derhuerst** [comment]
Can you have a look at what HTTP status code is being returned? If you get a `403` just like `ecstatic`'s source code implies, this is the explanation.

**Comment by dKab** [comment]
it's 404

**Comment by dpk-kakkar** [comment]
one can see the solution here :
https://stackoverflow.com/questions/23815695/how-do-i-load-a-file-in-a-parent-directory-using-http-server/45956694#45956694

**Comment by Jun711** [comment]
The workaround from the [stackoverflow link above](https://stackoverflow.com/questions/23815695/)  is NOT to access a parent directory and have your files in the same directory or child directories.
