### ISSUE TITLE
Daemon option.

### ISSUE THREAD

**Issue by sposmen** [indexzero/http-server#223]
Add the Daemon option.

**Comment by indexzero** [comment]
This is not the direction the project is going. Use another tool (like `forever` to daemonize http-server)

**Comment by sposmen** [comment]
Oky, `&` is working tks. To me is annoying to have multiple consoles opened while editors don't needed. But I love the project, tks!

**Comment by indexzero** [comment]
You can also try:

```
npm i forever http-server -g 
forever start `which http-server`
```
