### ISSUE TITLE
run server --ssl not found

### ISSUE THREAD

**Issue by ButuzGOL** [indexzero/http-server#224]
certs were build by this tutorial https://docs.nodejitsu.com/articles/HTTP/servers/how-to-create-a-HTTPS-server

22:32 ~SF_BUILD_ROOT master* ❯ http-server --ssl                                                    
Starting up http-server, serving ./ through https
Available on:
  https:127.0.0.1:8080
  https:192.168.0.102:8080
Hit CTRL-C to stop the server

When I go https://127.0.0.1/ gives me not found

**Comment by derhuerst** [comment]
> When I go https://127.0.0.1/ gives me not found

What kind of "not found" are you talking about? Can the browser connect to the server? Does it give you an HTTP status code?

**Comment by derhuerst** [comment]
Also, keep in mind that the tutorial that you used is quite outdated. This is significant when dealing SSL security and this is also the reason why Firefox doesn't seem to trust the certificate generated following this article. You can use a [self-signed SSL certs script from a repo of mine](https://github.com/derhuerst/shout/blob/master/scripts/self-signed-certificate.zsh) for example; In this case you would start the server with `http-server --ssl --cert self-signed.crt --key self-signed.key`.

**Comment by ButuzGOL** [comment]
Thanks my the problem was with port
