### ISSUE TITLE
how to find http-server logs in linux

### ISSUE THREAD

**Issue by UniKylin** [indexzero/http-server#228]
When http-server start , I can see so many logs in my console, how to find logs in linux system. which folder ?

**Comment by derhuerst** [comment]
By default, `http-server` logs to `stdout` (the console in your case). You can pipe its `stdout` to a file (e.g. `http-server . >> ./http-logs`.

Also, if you use a wrapper like [`forever`](https://www.npmjs.com/package/forever) or [`nohup`](https://en.wikipedia.org/wiki/Nohup), `stdout` will be redirected to a file automatically.

**Comment by UniKylin** [comment]
It would be a nice solution. thanks

**Comment by derhuerst** [comment]
@UniKylin What would be a nice solution? Writing `stdout` of a process to a file has already been solved by many tools, so putting this inside `http-server` wouldn't make sense.

**Comment by UniKylin** [comment]
Yeah. Http-server can meet my requirement. a lightly http tools would be the best.

**Comment by derhuerst** [comment]
what is "lightly http tools"?

**Comment by UniKylin** [comment]
...
