### ISSUE TITLE
[question] --cors not working for cross site requests

### ISSUE THREAD

**Issue by bhushanvaidya3** [indexzero/http-server#239]
--cors flag does not add 'Access-Control-Allow-Origin: *' to request header for some reason. Here is an extract from my package.json file:

"scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "http-server -a localhost -p 5000 --cors -c -3"
  }

Am I missing something ?

Thanks!

**Comment by derhuerst** [comment]
This works for me, on OS X 10.11.2. `Access-Control-Allow-Origin: *` is being sent.

**Comment by bhushanvaidya3** [comment]
It's not working on windows 7 for me. Node version is 5.5.0.

![image](https://cloud.githubusercontent.com/assets/10674378/12519914/a008004a-c10f-11e5-89cb-0d62bd98277e.png)

**Comment by bhushanvaidya3** [comment]
The web api I was testing against had token based authentication enabled hence it was actively refusing my request. My bad! --cors works fine.
