### ISSUE TITLE
conflict with hs npm package

### ISSUE THREAD

**Issue by arete** [indexzero/http-server#243]
hi if i install first hs https://www.npmjs.com/package/hs
and next http-server, /usr/bin/hs link to http-server and
link to hs package is delete.
please fix

**Comment by derhuerst** [comment]
This is because an executable `hs` is [in the `package.json` of http-server](https://github.com/indexzero/http-server/blob/db66b17e28105d4fd6d41913cd5a7cbe7ba1528f/package.json#L82).

I gree that `hs` as an alias for `http-server` can easily be done using shell aliases.

**Comment by indexzero** [comment]
Will see who else +1s this. Right now when I look at the `hs` package I see very few downloads and very low usage.

**Comment by derhuerst** [comment]
But people who use `http-server` that often certainly know how to create shell aliases.

**Comment by indexzero** [comment]
As a maintainer I don't feel like I can make that assumption safely. Nor do I have the data about the `hs` usage. Therefore, I'm going to leave this as is until there are enough +1s to change it.

**Comment by thornjad** [comment]
Closing for now since there have been no +1's in three years.
