### ISSUE TITLE
iPhone can not connect to local HTTP server over WiFi

### ISSUE THREAD

**Issue by smohadjer** [indexzero/http-server#249]
I can not open static HTML pages after I run http-server on my MacBook in iPhone 6s iOS 9.2, neither in 'Safari' nor in 'Chrome' browser when using: http://ip:8080

I am able to open the pages on Android phones and I'm also able to open the pages if I turn MacBook's WiFi off and on, but if I change the page and refresh the browser, it again fails to load the page and says that server has stopped responding or that Safari could not connect to the server.

Resetting network settings in iPhone didn't help, nor did turning off Cellular Data in iPhone settings. Any idea what's wrong?

**Comment by derhuerst** [comment]
Does the `http-server` process in the command line crash?

Can you ping your MacBook from your iPhone, using apps like [Fing](https://itunes.apple.com/de/app/fing-network-scanner/id430921107?mt=8)?

**Comment by smohadjer** [comment]
No, pinging from iPhone shows 0 received packets. If I turn WiFi off and on on Macbook ping works, but if I leave iPhone idle for a few minutes and ping again it ping fails again.

**Comment by smohadjer** [comment]
Also I can't reproduce the problem using the same iPhone in a different location with different router and different MacBook.

**Comment by derhuerst** [comment]
Well, if `ping`ing doesn't even work properly, then it's most likely not `http-server`'s fault. Please check your network configuration & firewalls.

Also, try if you can reach your MacBook on other protocols, e.g. AirDrop or printer sharing ([cups](https://de.wikipedia.org/wiki/Common_Unix_Printing_System)).

**Comment by derhuerst** [comment]
You might [check if your Firewall blocks node from listening on a port](https://support.apple.com/en-us/HT201642).

**Comment by smohadjer** [comment]
Firewall is off.

**Comment by derhuerst** [comment]
So this issue can be closed then?
