### ISSUE TITLE
Minor logging output protocol string missing slashes

### ISSUE THREAD

**Issue by robjens** [indexzero/http-server#251]
Minor enough to not want to do a pull request but big enough to make me want to post it. Since the change is arbitrary, I don't think the devs here will mind too much:

https://github.com/indexzero/http-server/blob/master/bin/http-server#L131

should probably be:

`logger.info(('  ' + protocol + '//' + details.address + ':' + port.toString()).green);`

Note the `+ '//' +` being added. Unless it is intentional to show `http:0.0.0.0:3000` (for example) but I don't think so. Protocol missing slashes is so unintuitive (why the colons so special?) that it is easy to miss, even if you just tested for it

**Comment by thornjad** [comment]
It looks like this was resolved by #220. Re-open if this is still an issue!
