### ISSUE TITLE
Closing Socket bug

### ISSUE THREAD

**Issue by bindingofisaac** [indexzero/http-server#252]
shutdown(sock, SD_SEND); 
doing that, on my client closes the entire connection,

**Comment by derhuerst** [comment]
Would you elaborate on that a bit more? Where do you call `shutdown`?

**Comment by bindingofisaac** [comment]
sure, I am writing a http client in C++, Once I finish sending my request I close the send part of my socket using shutdown(this was mentioned in MSDN), Operating System: Win7, compiler: Cl

**Comment by thornjad** [comment]
@bindingofisaac you should check the value of `SD_SEND`, make sure it's the direction you intend. Regardless, this doesn't appear to be an `http-server` issue.
