### ISSUE TITLE
health-check

### ISSUE THREAD

**Issue by ronag** [indexzero/http-server#254]
Would it make sense to add a simple `healthcheck` path to the server which responds 200. 

That way the server would work with HAProxy and NGINX.

**Comment by derhuerst** [comment]
Why would one put `http-server` behind nginx and not use nginx directly to serve files?

**Comment by derhuerst** [comment]
Also, a simple `HEAD` request on an existing path guarantees that the server works fine.

**Comment by thornjad** [comment]
I think the `HEAD` method makes more sense. You could set up a `/healthcheck` file for hitting with a `HEAD` request to check for health without needing a special path in `http-server`. Please reopen if that method doesn't work!
