### ISSUE TITLE
The SSL CA root certificate path parameter

### ISSUE THREAD

**Issue by waltom** [indexzero/http-server#258]
Please add path parameter to ssl ca root certificate.

The ready solution is attached.
[http-server.zip](https://github.com/indexzero/http-server/files/166890/http-server.zip)

**Comment by derhuerst** [comment]
As the maintainers of the project are really busy, would you mind submitting a pull request with the patch? The `http-server` file in the zip is quite outdated.

**Comment by waltom** [comment]
Added [request](https://github.com/indexzero/http-server/pull/259)
