### ISSUE TITLE
Allow specifying 404 page with CLI flag

### ISSUE THREAD

**Issue by tyrsius** [indexzero/http-server#262]
This is a feature request. Currently the `404.html` page is served on 404. This is useful, especially for SPA apps so that we can have a catch-all that still serves the `index.html`. However, it still requires duplicating the `index.html`.

Allowing us to specify the `index.html` *as the 404 page* would remove the need for this duplicate file.

It might also be generally useful to others, who knows =)

**Comment by derhuerst** [comment]
See #205.

**Comment by tyrsius** [comment]
This is a dupe
