### ISSUE TITLE
https port

### ISSUE THREAD

**Issue by szarouski** [indexzero/http-server#266]
If you're running site user https and you don't specify port setting, but specify address setting, in other words something like:
```
http-server -a static.site.ca -S --cert=site.cert --key=site.key
```
then http-server will use default port - 8080. That means that you'll only be able to load your site if you explicitly specify port in browser: `https://static.site.ca:8080`. If you would like to be able to access your site using just address: `https://static.site.ca`, then don't forget to set port to default value which browsers use: 443.
```
http-server -p 443 -a static.site.ca -S --cert=site.cert --key=site.key
```

It would be nice if http-server can do that out of the box.

**Comment by derhuerst** [comment]
One of the reasons why small adhoc HTTP servers don't do this is because you need `sudo` to listen on a port below 1000.

**Comment by szarouski** [comment]
I see, thanks.
