### ISSUE TITLE
http-server with simple username & password options

### ISSUE THREAD

**Issue by t3m** [indexzero/http-server#270]
Thanks for sharing this 'simple' awesome app. Is there a plan to add username/password options to it e.g. basic-auth? I don't intend to run it 24/7 with basic-auth but it prevent preying-eyes, just a piece of mind.

**Comment by ryanmjacobs** [comment]
Hey, I also wanted something simple like this. Something easy like, `--auth user:pass`. Any input or guidance would be well appreciated.

**Comment by roccomuso** [comment]
+1

**Comment by thornjad** [comment]
Fixed in #245

**Comment by vic1106** [comment]
I have tried the command, 
> http-server --username "test" --password "testing"
but it just never prompt a username & password input dialog.

Am I doing right with this command?

**Comment by thornjad** [comment]
@vic1106 are you trying that on v0.11.1, or when installed from the master branch? This feature is not yet released to npm.

**Comment by vic1106** [comment]
oh I just realise that.
I was using npm version which suppose not having this feature.

Then, I tried with master branch with this command.
`npm start --username "test" --password "testing"`
Not seeing the prompt too.
