### ISSUE TITLE
lowercase url also meets..

### ISSUE THREAD

**Issue by IAIAE** [indexzero/http-server#274]
there path/to/Test.js, and i request localhost:8080/path/to/test.js also meets. 
this makes 404 potentially.

**Comment by derhuerst** [comment]
@IAIAE On which operating system did you test that?

**Comment by IAIAE** [comment]
@derhuerst  
MAC OS EI Caption 10.11.4
node v6.0.0
http-server 0.9.0

**Comment by derhuerst** [comment]
OS X has – by default – a case-insensitive file system.

```shell
echo 'foo' >> bar
cat bar
cat Bar
```

Both `cat`s give the content of the lower-case `bar` file. This is why `http-server` should do the same.

**Comment by IAIAE** [comment]
@derhuerst thanks a lot.:)
