### ISSUE TITLE
Create HTTP-Server in code instead of in the C.L.?

### ISSUE THREAD

**Issue by XtremePlayzCODE** [indexzero/http-server#284]
How would I run HTTP-Server and set the index file and port all in code, instead of on the command line?

**Comment by derhuerst** [comment]
You can require [`http-server/lib/http-server`](https://github.com/indexzero/http-server/blob/19d2b82/lib/http-server.js) or use [ecstatic](https://github.com/jfhbrook/node-ecstatic), which has been made for this.

**Comment by XtremePlayzCODE** [comment]
Thanks, I was looking into Express anyways.

**Comment by derhuerst** [comment]
Express is the more flexible, but also more complex.
