### ISSUE TITLE
Make localhost.domain.com unavailable

### ISSUE THREAD

**Issue by matisoffn** [indexzero/http-server#285]
I'm using `http-server` to serve up a simple HTML/CSS website.  

In production, I'm running the command `http-server . -p 80 -d false -a 127.0.0.1`.

When I go to my domain.com, everything looks good.  However, when I go to localhost.domain.com the website can also be visited at that link.

How can I disable this?

**Comment by derhuerst** [comment]
This should be related to your domain's DNS settings. Check for an entry like this:

```
localhost  3600  IN  A  <ip-address>
```

**Comment by matisoffn** [comment]
Thanks
