### ISSUE TITLE
"keepalive" option?

### ISSUE THREAD

**Issue by killmenot** [indexzero/http-server#289]
Do you have behaviour similar to https://github.com/gruntjs/grunt-contrib-connect#keepalive ?

**Comment by derhuerst** [comment]
In which way would that work with `http-server`?

**Comment by killmenot** [comment]
@derhuerst I wanted to use `grunt-http-server` and I'd like to start a server and then run tests and expect server be shutdown.

```js
module.exports = function (grunt) {
  require('load-grunt-tasks')(grunt);

  grunt.initConfig({
    jshint: {
      options: {
        jshintrc: '.jshintrc',
        reporter: require('jshint-stylish')
      },
      files: {
        src: [
          'lib/**/*.js',
          'test/**/*.js',
          'Gruntfile.js'
        ]
      }
    },

    mocha: {
      test: {
        src: ['http://127.0.0.1:8282/testrunner.html'],
        options: {
          run: false
        }
      }
    },

    'http-server': {
      test: {
        app: 'test',
        cache: -1,
        runInBackground: true
      }
    }
  });

  grunt.registerTask('test', ['jshint', 'http-server', 'mocha']);
};
```
Then run `grunt test` to lint the code, start http server, run tests and expect the server will be stop when tests are passed.

Anyway, it's not a big deal for me because I excluded http-server from the package and run tests using file system

**Comment by derhuerst** [comment]
> I wanted to use grunt-http-server and I'd like to start a server and then run tests and expect server be shutdown.

`http-server` has been made for command line usage. If you really want to use it, you can kill the process after the tests ran. [Karma](http://karma-runner.github.io/1.0/index.html) can also server the testrunner over HTTP AFAIK.

**Comment by killmenot** [comment]
@derhuerst Thank you
