### ISSUE TITLE
Serving Content from RAM only

### ISSUE THREAD

**Issue by nsisodiya** [indexzero/http-server#291]
It is possible to add a feature so if that if somebody pass --ram argument than it will not server files from disk, rather it will server files from RAM only.
when http-server start, it scan the directory and load all files in RAM and then serve files from RAM only afterwards !

**Comment by derhuerst** [comment]
If think this is out of the scope of this module. There are battle-tested solutions for creating RAM-based virtual file systems, which `http-server` could serve.

**Comment by bitliner** [comment]
It would be useful for making deployments without downtime: while replacing the files in the filesystem (e.g. removing, adding files) you can still access the old file of the server (because they are in RAM).

**Comment by thornjad** [comment]
I do think this is out of scope for `http-server`, however this could be a good opportunity for another project, something like `ram-http-server` (or a much better name) which we could work alongside! More specifically, the file serving is done by `node-ecstatic`, which could be swapped for something that that serves from RAM (or from other non-disk locations).
