### ISSUE TITLE
Cannot GET png images

### ISSUE THREAD

**Issue by midhunadarvin** [indexzero/http-server#298]
Hi,

I am unable to retrieve .png images from the server. It shows the following message.

`Cannot GET /images/my-image.png`

It however works for all other static file requests. It allows jpeg, but It doesn't allow png. Can anyone help?

**Comment by wangyangkobe** [comment]
@midhunadarvin 
I can get png imgaes.
Which directory do you put "my-image.png"?

I put 'pass.png' in "/public/img/images", an i use link [http://localhost:8080/img/images/pass.png](http://localhost:8080/img/images/pass.png) , i can access the png image.

**Comment by EugeneAndrievsky** [comment]
I guess it has happened because you forgot copy your new image into /build directory

**Comment by thornjad** [comment]
@midhunadarvin Do you still see this issue on the latest versions of http-server and node?

**Comment by midhunadarvin** [comment]
@thornjad I checked with http-server. I was able to view the images. I guess it might have been something with my node server back then. I am closing this issue.
