### ISSUE TITLE
http-server's concurrency capability in production environment

### ISSUE THREAD

**Issue by UniKylin** [indexzero/http-server#302]
What is the concurrency capability of http-server in the actual production environment？ Have simulation test.

**Comment by derhuerst** [comment]
You can easily test that usin load testing tools like [artillery](https://github.com/shoreditch-ops/artillery).

**Comment by UniKylin** [comment]
Yeah, a nice load testing tool

**Comment by DiegoZoracKy** [comment]
@UniKylin do you have some results to share?

**Comment by derhuerst** [comment]
Some thoughts on this:

I'd guess it really depends on the storage you use and how you access the data. Modern operating systems will cache hot files in-memory, so if you request the same file all the time, it might not comparable to real-world usage.

Also the kind of disk will play a significant role, wether it's RAM, SSD or HDD.

**Comment by thornjad** [comment]
If anyone is interested in researching this, I'd be very interested in the results. However I'm closing for now due to inactivity.
