### ISSUE TITLE
Redirect http to https ?

### ISSUE THREAD

**Issue by Windyo** [indexzero/http-server#303]
This may be a very siple one, but I am unable to ind how to conigure http-server to redirect requests over http to https. which means that querying mydomain.com gives a "the server served no content" error instead of the content, because users don't think about adding the s to http.

**Comment by derhuerst** [comment]
You could have `http-server` listen on port `443`, serving over HTTPS. Then, setup an HTTP proxy, listening on port `80` and redirecting to HTTPS.

**Comment by Windyo** [comment]
When you say http proxy do you mean with http server or should I use something like nginx?

**Comment by derhuerst** [comment]
Something like [`node-http-proxy`](https://github.com/nodejitsu/node-http-proxy#using-https) might work.

**Comment by Windyo** [comment]
cool thanks
