### ISSUE TITLE
Handling intermediate ssl certs ?

### ISSUE THREAD

**Issue by Windyo** [indexzero/http-server#305]
I only see one option for the ssl cert, how should we reference the main cert and the intermediate one?

**Comment by derhuerst** [comment]
`http-server` uses `union`, [which calls `createServer` on `http`, `https` or `spdy` respectively](https://github.com/flatiron/union/blob/6ece680/lib/core.js#L87-L96). [`https.createServer`](http://jannis-mbp.local:54418/Dash/hjthuzjx/nodejs/api/https.html#https_https_createserver_options_requestlistener) and [`spdy.createServer`](https://github.com/indutny/node-spdy#api) both use [`tls.createServer`](http://jannis-mbp.local:54418/Dash/hjthuzjx/nodejs/api/tls.html#tls_tls_createserver_options_secureconnectionlistener) under the hood, **which accepts `cert`, `key` and `ca` option.

(I know that wasn't obvious 😁)

**Comment by Windyo** [comment]
@derhuerst okay,  thanks! 

So... Just to be clear I need to manually edit the http-server file and add my intermediate cert as ````ca```` in the createserver method? 

Sorry if that is unclear,  I am VERY new to all of this.

**Comment by derhuerst** [comment]
> So... Just to be clear I need to manually edit the http-server file and add my intermediate cert as `ca` in the createserver method? 

I haven't tried this, but it looks like you can just pass `ca` as a property of `options.https`. [It looks like it will be passed through to `union.createServer()`.](https://github.com/indexzero/http-server/blob/fed98f2dbb87f1ea7a793e48a1975c20c9e970fa/lib/http-server.js#L128-L132)

**Comment by Windyo** [comment]
Thanks for answering !

So I edited the http-server file created after install by node, added an I argument to use to pass the ca, and added the ca line to options.https as you said.

It worked perfectly, now my doesn't throw errors because of the cert. Thanks :)

I would create a pull request but I'm not sure it would be interesting, seeing as you guys have quite a lot of them open already. Let me know :)

**Comment by derhuerst** [comment]
> I would create a pull request but I'm not sure it would be interesting, seeing as you guys have quite a lot of them open already. Let me know :)

I'm not really an expert in SSL stuff, but isn't it possible to "embed" the chain into the certificate directly? At least when using Let's Encrypt, I pass `fullchain.pem` as `cert`.

**Comment by Windyo** [comment]
Well I tried by cat-ing the two files together like for nginx as ````cat  intermediate.crt >> public.crt```` but I had an EOF error. Tried all possible permutations,  but no dice. Hence this issue in the first place

**Comment by derhuerst** [comment]
[SSLLabs shows me the certificate chain for `https://transport.rest/`](https://www.ssllabs.com/ssltest/analyze.html?d=transport.rest&latest), even though I just used the Let's Encrypt `fullchain.pem` as `cert`. So it is possible.

**Comment by Windyo** [comment]
Okay,  didn't work with a geotrust one.Gave me cert, intermediate,  and key as separate files. 
Closing the issue in any case,  it's solved.  😊
