### ISSUE TITLE
Support serving of Angular HTML5 mode projects

### ISSUE THREAD

**Issue by ablankenship10** [indexzero/http-server#306]
I am serving an angular js project in development using the http-server and have HTML5 mode enabled so I can view URLs such as: localhost:8080/my-account/dashboard. This works fine for the most part until I need to refresh the page on any page that isn't the root page ( / ). For this to work the server needs to actually serve localhost:8080/index.html and let the app deal with the rest of the route.

Apache can do this with .htaccess / mod_rewrite. Is it possible that http-server could support a similar rewrite rule setup?

**Comment by 75lb** [comment]
would something like the [`ws --spa index.html`](https://github.com/lwsjs/local-web-server/#single-page-application) behaviour solve this and #80?

**Comment by BigBlueHat** [comment]
Closing this in favor of a README update to show how to "self-proxy": https://github.com/indexzero/http-server/issues/338#issuecomment-460648032
