### ISSUE TITLE
Scrolling stops working

### ISSUE THREAD

**Issue by beckah** [indexzero/http-server#310]
So I've noticed that if I run http-server and host a local site, I can not scroll on that site. When I stop the server, I can scroll. Any help would be much appreciated.

**Comment by derhuerst** [comment]
That does not sound like it is related to http-server. What file do you serve with it?

**Comment by beckah** [comment]
index.html

It started working fine after I uninstalled http-server

**Comment by derhuerst** [comment]
Did the `index.html` contain any special code that prevented scrolling as long as it was loading?

**Comment by beckah** [comment]
No. Same code works on another one of my computers. However, just for the heck of it, I uninstalled and reinstalled again and it's working. Not sure what magic took place, but definitely feel free to close the issue.

**Comment by winterblack** [comment]
I am having the same issue. I'm running an http-server to get around CORS issues with my back end. If I open my index.html from the file, the page scrolls just fine, but when I serve it over http-server, scroll stops working.

**Comment by winterblack** [comment]
Uninstalling and reinstalling didn't work at first, but while I was trying to recreate the issue, it went away. Very strange.
