### ISSUE TITLE
Forgot to release new version?

### ISSUE THREAD

**Issue by franciscop** [indexzero/http-server#313]
I see in https://github.com/indexzero/http-server/issues/56 that the --gzip feature was added (thanks), and it's also in the readme.md. However it [doesn't seem to be in any release yet](https://github.com/indexzero/http-server/compare/0.9.0...master).

So could you please release `http-server 0.10.0` with this feature? I would do it myself but I cannot `npm publish` anything. Thank you

**Comment by cgatian** [comment]
How can they state "It is powerful enough for production usage" when gzip isn't supported?

**Comment by StevenSchrembeck** [comment]
Please release v 0.10.0

**Comment by franciscop** [comment]
I think this repo is unmaintained...

**Comment by derhuerst** [comment]
Not entirely, but there's not a lot of work being done. Will think about offering to maintain it.

**Comment by franciscop** [comment]
@derhuerst well we'd need @indexzero input for this issue anyway since [indexzero's the only collaborator in npm](https://www.npmjs.com/package/http-server)

**Comment by greenSnot** [comment]
+1

**Comment by BigBlueHat** [comment]
I'm collecting a couple of key things folks want for a v0.10.0 release (see the [v0.10.0 related milestone](https://github.com/indexzero/http-server/milestone/1)). If you're still here (and I hope you are!), tests and such are most welcome!

**Comment by StevenSchrembeck** [comment]
Thanks @BigBlueHat ! This is one of my favorite npm packages. It was my first "whoa" moment with node/npm, coming from a Java environment where it takes 2 weeks to spin up a server.

**Comment by franciscop** [comment]
Hey @BigBlueHat why not splitting it into two releases? `0.10.0` with **does gzip, which is already in the code** and `0.11.0` for new features yet-to-be-implemented. In this way we can instantly benefit from this and then benefit again when the `0.11.0` is released. GZIP support was added almost 1 year ago while the corresponding version hasn't been released yet.

**Comment by BigBlueHat** [comment]
Yeah. Good call. I'll toss another milestone up and move everything else over to that one.

Stay tuned! 😁
