### ISSUE TITLE
There's some option to allow customize the list of files

### ISSUE THREAD

**Issue by rkmax** [indexzero/http-server#317]

**Comment by derhuerst** [comment]
In which way do you want to customize it? Right now, there's no option, except enabling and disabling directory indexes entirely.

**Comment by rkmax** [comment]
Example adding css or a different template

**Comment by derhuerst** [comment]
No. `http-server` is not exactly meant for that, just as a basic file server. Check [my project casket](https://github.com/derhuerst/casket) or [droppy](https://github.com/silverwind/droppy) (there's lots of other alternatives).

**Comment by derhuerst** [comment]
You could also build your own using [express](http://expressjs.com/)/[koa](http://koajs.com/), using [serve-static](https://github.com/expressjs/serve-static#readme) for serving files.

**Comment by rkmax** [comment]
Thank you @derhuerst
