### ISSUE TITLE
Available on http:127.0.0.1:8000 (no double slash?)

### ISSUE THREAD

**Issue by jlmakes** [indexzero/http-server#327]
Using version `v0.9.0` on Node `v6.3.0`, and it starts up a server at `http:127.0.0.1:8000`...
which without the `//` in the address makes it unusable.

To be clear, if I manually navigate to `http://localhost:8000` for example, the server is running... but being able to Cmd + Click the address is a great convenience and no longer works.

**Comment by derhuerst** [comment]
Does #307 solve it for you?

**Comment by jlmakes** [comment]
I made that change @derhuerst and nothing's different. In fact, I wasn't seeing any changes I made make a difference... maybe I was doing it wrong?

`cd ~/.nvm/versions/node/v6.3.0/lib/node_modules/http-server/bin` && `vi http-server`

**Comment by jlmakes** [comment]
You know what...

I just discovered this is related to my current project somehow.
When I run `http-server` outside of this project, it performs as expected.

**Comment by derhuerst** [comment]
you can use `npm prefix` and `npm prefix -g` to find out where your node modules will be stored. Also `npm ls --depth 0` and `npm ls -g --depth 0` will help you.

To install my PR, just do `npm install http-server@derhuerst/http-server`, which installs my fork.

**Comment by jlmakes** [comment]
I'm just going to go ahead and close this, because after cleaning up my system node modules, my current nvm modules, and my project modules...

Everything works as expected.
