### ISSUE TITLE
log ip address of client 

### ISSUE THREAD

**Issue by snimavat** [indexzero/http-server#328]
is there a way to log the ip address of the client ?

**Comment by derhuerst** [comment]
afaik there's not way.

**Comment by snimavat** [comment]
@derhuerst can we have this please

**Comment by derhuerst** [comment]
@snimavat The maintainers of this module are pretty busy, telling by the number of open issues & PRs. Let's wait for them to give an opinion on wether they want this functionality or not.

If you wanted to do this by yourself, you could implement your own `options.logFn`.

**Comment by thornjad** [comment]
Duplicate of #184
