### ISSUE TITLE
Follow symlinks

### ISSUE THREAD

**Issue by armoucar** [indexzero/http-server#341]
I haven't found any option to allow `http-server` to follow OS symlinks.

**Comment by derhuerst** [comment]
They seem to be working.

```shell
mkdir test; cd test
mkdir foo
touch foo/bar
ln -s foo baz
npm install http-server
http-server -p 3000 . &
curl 'http://localhost/baz/'
```

**Comment by armoucar** [comment]
my bad, they do work... sorry :(

**Comment by derhuerst** [comment]
Please close the issue in this case. This module is barely maintained, so keeping the noise of answered questions low is important. Thanks!
