### ISSUE TITLE
端口有冲突时没有提示

### ISSUE THREAD

**Issue by teal-front** [indexzero/http-server#343]
默认是8080端口，没有冲突提示

**Comment by dolanmiu** [comment]
你要说英文，鬼佬不明日，戆𨳊

**Comment by oceanpad** [comment]
default port is 8080，when has conflict with other software, there has no error prompt.
@indexzero

**Comment by heekei** [comment]
每次进来都要来看看这条issue，哈哈哈，莫名喜感

**Comment by oceanpad** [comment]
@heekei 我擦，哈哈哈哈

**Comment by indexzero** [comment]
Howdy folks. Would someone mind translating? I don't want anything to get lost in translation if I just copy / paste this into Google translate.

**Comment by oceanpad** [comment]
@indexzero just ignore it, we are saying there has not error prompt when the port is duplicate(the port had auto change to other ports). The others messages are just joke, just ignore them.

**Comment by indexzero** [comment]
Alright. Thanks. Closing this issue then.
