### ISSUE TITLE
do not support .shtml

### ISSUE THREAD

**Issue by jackie19** [indexzero/http-server#344]

**Comment by derhuerst** [comment]
This server does not support any kind of server-side (pre)processing of rendering, so `.shtml` are not supported. It would require a thorough rewrite and a far more sophisticated codebase. Also, SHTML doesn't seem to be the technology that most people use for templates & server-side rendering.

**Comment by BigBlueHat** [comment]
@jackie19 feel free to reopen this with a more complete explanation. I'd be curious what was broken or what you'd wanted here. Thanks!
