### ISSUE TITLE
i try to run for jekyll project and have issues

### ISSUE THREAD

**Issue by rubenmedios** [indexzero/http-server#345]
My Jekyll project runs in: `http://127.0.0.1:4000/tucavacuarto/`

then i try to run this:

`http-server http://127.0.0.1:4000/tucavacuarto/`

and the results is this:

`Starting up http-server, serving http://127.0.0.1:4000/tucavacuarto/
Available on:
  http://192.168.0.101:8080
  http://127.0.0.1:8080`

but when i run the web server in the browser or cell phone, i return this in the console:

`[Tue Feb 14 2017 11:03:09 GMT-0400 (Hora estándar de Venezuela)] "GET /" "Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3012.0 Safari/537.36"
[Tue Feb 14 2017 11:03:09 GMT-0400 (Hora estándar de Venezuela)] "GET /" Error (404): "Not found"`

can i run this for test my project from cell phone? Thanks in advance

**Comment by derhuerst** [comment]
The first argument you can pass to `http-server` is the directory to serve, not the URL it will be available at. Try `http-server tucavacuarto` being in the directory that contains `tucavacuarto` or `http-server` being in `tucavacuarto`.

**Comment by rubenmedios** [comment]
i try erasing /tucavacuarto from ur in jekyll project and navigate the server url sucessfully in the browser but in the cell phone can`t load the css.

¿how to pass the port in the url? ¿`http-server -p:4000`? i dont know how to do

**Comment by derhuerst** [comment]
jekyll doesn't have a specific port afaik. you can specify the port with `http-server -p 1234`.

**Comment by derhuerst** [comment]
> i try erasing /tucavacuarto from ur in jekyll project and navigate the server url sucessfully in the browser but in the cell phone can`t load the css.

Give me a proper description on what you did. Where did you run `http-server`, where's your content/HTML?

**Comment by rubenmedios** [comment]
Thanks @derhuerst i can run from port, only change the absolute paths in jekyll (look for localhost) and works! i'm excited

**Comment by derhuerst** [comment]
Nice to hear that! Would you mind closing the issue if all your questions have been answered?

**Comment by BigBlueHat** [comment]
Looks like y'all got this sorted! Glad it's working for you. 😁
