### ISSUE TITLE
CORS option not working for me

### ISSUE THREAD

**Issue by mnemanja** [indexzero/http-server#347]
From all the issues here and the documentation I've gathered it should be pretty easy.
`http-server build/ -p 3010 --cors`

However I'm not seeing any change in the Request headers.
![image](https://cloud.githubusercontent.com/assets/1423218/23463136/cac10a38-fe90-11e6-83c9-78e379344271.png)

The console reports the following
```
Fetch API cannot load PATH No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3010' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

**Comment by derhuerst** [comment]
As you scrambled the picture, I cannot see where the request went to. I can only tell from the `Host` request header that contains `confluence.intra.qualitype.de`.

With CORS, only the server targeted by the request can allow cross-origin communication. You seem to have enabled CORS for `localhost:3010`.

Please provide more details about your setup.

**Comment by setry14** [comment]
As an **alternative** to http-server `cors` flag, you can always get a filter added on the hosting API's `web.xml` if you have friendly developers there.

Filter looks like this - 
`<filter>

       <filter-name>CorsFilter</filter-name>

       <filter-class>org.apache.catalina.filters.CorsFilter</filter-class>

     </filter>

     <filter-mapping>

       <filter-name>CorsFilter</filter-name>

       <url-pattern>/*</url-pattern>

     </filter-mapping>`

**Comment by derhuerst** [comment]
@setry14 Note that many webservers don't have this functionality or at least not in the form of a `web.xml` file. If @mnemanja owns the server they try to query, then they can easily change the config to allow CORS. Also note that enabling CORS for `*` should be throroughly thought about.

**Comment by mnemanja** [comment]
Hi @derhuerst since I've forgot to obfuscate everything then it really doesn't matter anymore :)
![image](https://cloud.githubusercontent.com/assets/1423218/23498129/74dcb086-ff26-11e6-94ae-f3b24f4053df.png)

How can you tell that the CORS is enabled? I don't see the `Access-Control-Allow-Origin` among the request headers properties.

As for my setup I'm serving a build of the application made using the create-react-app boilerplate.
Within it I'm trying to access the locally hosted [Confluence](https://www.atlassian.com/software/confluence?_mid=135e869f7e76b0c7f2340ca650b17d8a&aceid=&adposition=1t1&adgroup=9509269081&campaign=183106561&creative=179588672558&device=c&keyword=confluence&matchtype=e&network=g&placement=&gclid=CLK9-LSut9ICFe0W0wodOCgNvA). 

I have tried fixing this locally with this [chrome extension](https://chrome.google.com/webstore/detail/allow-control-allow-origi/nlfbmbojpeacfghkpbjhddihlkkiljbi?utm_source=chrome-app-launcher-info-dialog) and then it works.

**Comment by mnemanja** [comment]
I might be in fault here, and the issue is on the resource's part.
However I'd appreciate knowing how to distinguish if the cors is working as you've mentioned. 

p.s. I've accidentally clicked "close" :)

**Comment by derhuerst** [comment]
With your setup, it doesn't really matter if the `--cors` flag you're using to server on `localhost:3010` is set or not. As I stated in my previous post, you need to enable CORS at `confluence.intra.qualitype.de`, not on `localhost:3010`.

If the headers show up depends on the type of request you're sending (`GET`, `POST`, `PATCH`, etc) and the `fetch` options you passed. See [MDN on CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS#Examples_of_access_control_scenarios).

**Comment by mnemanja** [comment]
Thanks @derhuerst.
I appreciate your quick responses.

Cheers,
Nemanja

**Comment by TeodorKolev** [comment]
--cors option do nothing for me. I have tried http-server --cors and http-server --cors='*'
No success

**Comment by mnemanja** [comment]
Hi @TeodorKolev,
Like @derhuerst mentioned above, it was not about setting the server to send a cors request, but whether the destination point accepts it or not.

When you make a request that request has to be accepted (whitelisted) on the server serving the endpoint in question.

Hope this helps.

**Comment by TeodorKolev** [comment]
Hello @mnemanja I do not agree. I can access destination point with proxy on deve env with no problem. Also command --cors did not set CORS header at all

**Comment by mnemanja** [comment]
@TeodorKolev,
Are you using the 'http-server --cors' for serving your application or for the API?

**Comment by TeodorKolev** [comment]
@mnemanja yes, I do

**Comment by mnemanja** [comment]
Sorry, perhaps I wasn't clear enough.
What are you using the `http-server` with `--cors` for?
Is it for serving your application or for serving the backend that handles the API that you are trying to access?

**Comment by TeodorKolev** [comment]
I start production dist folder with it

**Comment by mnemanja** [comment]
I believe there lies the confusion.

When requesting resources from your client you can make requests to whatever you wish so you can serve your client (dev or production) with just `http-server` because the browser is the one deciding whether or not to allow the connection between the client and the server depending on the server configuration by first sending the preflight request (options). There you'll not see your headers.

When serving the API, there you should have the CORS enabled and configured.
So, in case you would use http-server or something else to serve your API you would use`http-server --cors` + configuring the whitelist in the server application to accept the requests coming from your client application.

**Comment by TeodorKolev** [comment]
I have configurated proxy in proxy.conf.json which works perfectly fine in dev env.
