### ISSUE TITLE
Error: getaddrinfo ENOTFOUND http://127.0.0.1 http://127.0.0.1:8080

### ISSUE THREAD

**Issue by yangchongduo** [indexzero/http-server#349]
Error: getaddrinfo ENOTFOUND http://127.0.0.1 http://127.0.0.1:8080
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
error Command failed with exit code 1.

请问为什么？

**Comment by derhuerst** [comment]
Please provide more details on what you were trying to do and what your setup looks like.

**Comment by BigBlueHat** [comment]
@yangchongduo that happens when something's already listening on port 8080. If you specify a different port, things should work as expected. Thanks!

**Comment by shen-lan** [comment]
`http-server -P 10.100.23.230:8081`
I have same problem.

**Comment by shen-lan** [comment]
I solved the problem.
`http-server -P http://10.100.23.230:8081`
Don't forget to add http protocol
