### ISSUE TITLE
How can I get clean URLs?

### ISSUE THREAD

**Issue by wamoyo** [indexzero/http-server#351]
I have some html files that I want to serve up, but I don't want to put the file extensions in the names of the files, because I want clean URLs. 

Can I have html files with names like `index`, `about`, and still serve them up like html files to port 8080?

The `-e` options doesn't seem to work when doing `http-server -e html site/`. I get no character encoding declared errors in firefox and 404's on the console.

If I do `http-server site/ -e html` then firefox promps me to download the index and about files.

**Comment by BigBlueHat** [comment]
@wamoyo do you have any interest in exploring / coding this?

**Comment by wamoyo** [comment]
I ended up doing a bit of a work around, but I did fork this repo and make some adjustments. I'm happy to explore, absolutely : )

**Comment by BigBlueHat** [comment]
@wamoyo are you looking for something more than what fixing #160 would provide?

**Comment by wamoyo** [comment]
So, the fact the html is the default helped me out, and then I ended up creating both page.html and page without the .html extension files for each of my pages. Then pushing the ones without the extension up to S3 with a content-type set to 'text/html'. It works just fine for my purposes. 

There's another challenge with this, which is that I can't tell pug (my html template language) to output files with no extension. 

If I wanted clean URLs and nothing else, I'd need to fix the issue at the template, local static server, and S3 level. I opted to just fix the third, and rely on http-server's default of type html. This works, and has the added benefit that if someone were to type the .html extension, they'd still get the page they asked for.

**Comment by BigBlueHat** [comment]
Good to know. I'll focus my efforts on #160 then, and revisit more complex options later.

For my part, I'd like something similar to the [File Handler in wptserve](http://wptserve.readthedocs.io/en/latest/handlers.html#file-handlers) (a Python-based server for running the Web Platform Tests system at the W3C).

I'd like `index` to map to `index.html` (if it exists...and possibly through a series of other media types if found...perhaps optionally). I'd also *very* much like their `.headers` file thing for adding arbitrary headers to responses per file or directory. Super handy for all kinds of things. But decidedly a different issue. 😄 

I'm going to close this in favor of focusing on #160 and/or filing additional more fixable bugs/features. :wink:

Thanks for the feedback @wamoyo!
