### ISSUE TITLE
Option to close the browser window when I close the http-server [suggestion]

### ISSUE THREAD

**Issue by shimakazekai** [indexzero/http-server#353]
I run the http server with -o option that open a browser window.

Can you please add an option that closes the browser window when I shut down the script? 

It should be a simple kill on the pid but it's a bit problematic to implement on my own on windows.

**Comment by BigBlueHat** [comment]
This one seems a bit out of scope and directly tied to testing. Opening a browser window when the server runs is already a "nice to have." Closing it (especially via killing a process) seems a bit risky relative the the gains you'd get.

It's likely "easier" to find a script that kills a process relative the the appearance/disappearance of another script.

If you disagree, I'm happy to take a look at it more if you can find some cross-platform module that would help this happen.

**Comment by SelaOAL** [comment]
I run bash on windows (MinGW) and it looks like it doesn't really work if I try to kill chrome with a script.
For example if I run:

`./chrome.exe & echo $!`

and then `kill {the pid that was printed}`

the chrome window doesn't close even though I'm getting the following afterward:
`[1]+  Done                    ./chrome.exe`

So yeah I'd be happy if you could help with that.

**Comment by BigBlueHat** [comment]
Thanks @SelaOAL. I'm running the same stack here, fwiw. However, this feature's not likely to be a priority and falls into the "nice to have" category. That said, if code magically appeared here, I'd be happy to take a look. 😸 

Thanks!
🎩
