### ISSUE TITLE
Server / page hangs when I have template strings in a script / tag (js-ish) file.

### ISSUE THREAD

**Issue by jmk2142** [indexzero/http-server#355]
Strange bug. Not sure it's an http-server issue, maybe a bug in a dependency as I can generate the same problem in various server solutions (e.g. reload, lr-http-server, etc.) Anyway, thought maybe someone here might have a better insight. I'm using RiotJS and http-server / watch-http-server to develop. My page stopped responding when I started using template strings in my file.

I'm loading the files in an index.html like this:

<img width="917" alt="screen shot 2017-04-02 at 7 10 51 pm" src="https://cloud.githubusercontent.com/assets/13051415/24591811/1c8dc4fe-17d8-11e7-8797-6a641ea3db17.png">

What happens is when I include a template string like this in my tag file (comments-mine.tag):

<img width="986" alt="screen shot 2017-04-02 at 7 00 14 pm" src="https://cloud.githubusercontent.com/assets/13051415/24591752/a70a309c-17d6-11e7-95f7-e93ea456370a.png">

The Network panel gives me a warning: Caution: request is not finished yet!

<img width="1307" alt="screen shot 2017-04-02 at 7 01 32 pm" src="https://cloud.githubusercontent.com/assets/13051415/24591763/0131e6f0-17d7-11e7-99c7-b69cef3ffc8a.png">

This hangs the page. Nothing in the browser window will work until the hang frees itself. With one or two of these template string lines, the page will eventually (after a long delay) become responsive again. However, with many of these - the browser will try to kill the page.

I've duplicated this issue in Firefox as well. By simply commenting out the template string and replacing it with string cats, the page loads fine, see image:

<img width="1004" alt="screen shot 2017-04-02 at 7 06 49 pm" src="https://cloud.githubusercontent.com/assets/13051415/24591792/8c419330-17d7-11e7-971f-b68339700743.png">

Result:

<img width="1309" alt="screen shot 2017-04-02 at 7 07 50 pm" src="https://cloud.githubusercontent.com/assets/13051415/24591802/b2393228-17d7-11e7-891f-a351798c964a.png">

Any ideas where the issue lies?

EDIT: Seems to change the outcome if I add more or less `${}` in the line. Or `/` chars. Or whether it's inside `[ ... ]`. Something in the way the server is parsing the raw stuff it transfers?
See examples:
```
Hangs (one ${...})
updates[`comments/public/${comment.id}/`] = comment;

Works
updates[`comments/public/${comment.id}`] = comment;

Hangs (two ${...})
updates[`users/${user.uid}/${comment.id}`] = comment;

Works
updates[`users/${user.uid}/${comment.id}/`] = comment;

Template String Pattern outside of brackets [...]
Works (this pattern hangs if in brackets)
var publicRefStr = `comments/public/${comment.id}/`;
updates[publicRefStr] = comment;

Hangs (two ${...} still)
var userRefStr = `comments/users/${user.uid}/${comment.id}`;
updates[userRefStr] = comment;

Works (two ${...})
var userRefStr = `comments/users/${user.uid}/${comment.id}/`;
updates[userRefStr] = comment;
```

**Comment by BigBlueHat** [comment]
Pretty confident this isn't an http-server related issue. Feel free to open a re-open this if you can narrow the bug down to something directly http-server related. Thanks!

**Comment by jmk2142** [comment]
Yeah. Figured. Any idea as to which dependency might be a good place to start hunting this down?

**Comment by BigBlueHat** [comment]
@jmk2142 something frontend / template related, I'd reckon.
