### ISSUE TITLE
where are the maintainers? 

### ISSUE THREAD

**Issue by antonioaguilar** [indexzero/http-server#356]
I understand this is an open source project and maintainers are not obliged to provide prime support but several users have posted issues #355, #354, #353, #352, #351, #348 and these issues have been opened for almost a month without a single comment from the maintainers. I'm just wondering if the http-server project has gone stale?

**Comment by BigBlueHat** [comment]
@antonioaguilar I'd been wondering the same thing! I reached out to @indexzero who's said that the project is considered "stable" for what he'd meant it to be. However, there are obviously folks who want(ed) some additional things such as gzip and clean URLs (re: the issues you linked to).

Some of these issues state possible solutions, some don't, most don't have PRs. There are, however, several possible PRs that pass tests (though they may not have their own), and I'm keen to help get some of those (at least) merged.

If any of the issues you posted are needed by your project, and you're up for writing/finding some PRs (with tests!), I'd be happy to help get them merged.

Thanks for being here and for starting this conversation!
🎩

**Comment by BigBlueHat** [comment]
I'm working on curating the existing PRs toward a v0.10.0 release:
https://github.com/indexzero/http-server/milestone/1

Happy to have your help testing and curating the awesome hiding in the issues and such!

Cheers.
