### ISSUE TITLE
Focus tests on Node LTS releases

### ISSUE THREAD

**Issue by BigBlueHat** [indexzero/http-server#359]
The Travis file currently lists `0.10`, `0.12`, and `4.1`:
https://github.com/indexzero/http-server/blob/master/.travis.yml#L3-L6

Based on [the LTS schedule](https://github.com/nodejs/LTS#lts-schedule1), I think it's prudent (sane) to:
- [x] drop 0.10
- [x] (possibly) drop 0.12
- [x] add 6.0
- [ ] add 8.0 (once Travis is ready for that)

Think that should limit the pain of maintenance a bit. I'm primarily looking for feedback about dropping `0.12`.

Thanks!

**Comment by franciscop** [comment]
Node.js 8.0.0 is [dropping in few days](https://github.com/nodejs/node/pull/12220), might as well include it. Though it won't be LTS until 6 months later, but it everything goes according to the plan 8.0 => 8.x should be totally compatible.

**Comment by BigBlueHat** [comment]
Thanks @franciscop! Added it to the list.

**Comment by WesleyDRobinson** [comment]
In a [nodejs.org survey](https://nodejs.org/static/documents/2016-survey-report.pdf) April 2016, ~18% reported using `0.12` in production with 80% scheduled for upgrade to `v4` within the year. Maybe 2017 survey results will be released soon and offer more recent data.
Seems safe to drop.
![image](https://cloud.githubusercontent.com/assets/10506091/26022487/8663f5f4-375b-11e7-88ba-5e1c4e3dc46b.png)

**Comment by franciscop** [comment]
Version 8.0.0 is about to drop soon

**Comment by yamboy1** [comment]
I would drop 0.12 because it doesn't support es6

**Comment by BigBlueHat** [comment]
#370 has the goods. It's using Node.js 4-7 and removes some cruft from ages past.

Holler if something looks off. :grin:
