### ISSUE TITLE
Question: Also possible to only proxy specific URL's in instead of all ?

### ISSUE THREAD

**Issue by StefH** [indexzero/http-server#361]
`--proxy` : Proxies all requests which can't be resolved locally to the given url.

However, I want more control on the exact url pattern, something like **webpack-dev-server**:

```
proxy: { '/api/*': { target: 'http://localhost', secure: false } }
```

Is this possible ?

**Comment by Hunter84** [comment]
I'm needing this as well and it's kind of urgent.  Any updates?

**Comment by BigBlueHat** [comment]
@Hunter84 if you're in a hurry, I'd recommend looking for a more configurable server at this point. It's not clear (yet) how this would be handled or even if it's something that `http-server` will be doing...at least not in the short term.

Apparently `webpack-dev-server` has this feature, so perhaps start there?

**Comment by Hunter84** [comment]
@BigBlueHat yeah I figured.  Thanks.

**Comment by BigBlueHat** [comment]
@Hunter84 I'd certainly be curious about what you find. 😄

**Comment by zengxiaoluan** [comment]
你是怎么解决这个问题的呢？

**Comment by BigBlueHat** [comment]
@zengxiaoluan my guess is that they solved it by creating a customized version of https://github.com/indexzero/http-server/blob/master/lib/http-server.js That's the best place to start for non-command-line-only use. Cheers!

Also, closing this with an eye toward #377.
