### ISSUE TITLE
Default document

### ISSUE THREAD

**Issue by Robouste** [indexzero/http-server#366]
Is there an option to set the default document ? 

Example : 

index.html
index2.html -> get this one when no files specified in the URL (http://localhost:8080)

**Comment by ycmjason** [comment]
Except for no file specified in the URL. I think it would be very useful to be able to set a default document upon 404. This would be particularly useful for frontend routing like angular or in other frameworks.

**Comment by ycmjason** [comment]
My suggestion is similar to the -P option

```
-P or --proxy Proxies all requests which can't be resolved locally to the given url. e.g.: -P http://someurl.com
```
I think it would be great if we could proxy a request to a file.

**Comment by BigBlueHat** [comment]
Take a look at #369 which is a clearer proposal for handling a default file scenario than overloading the meaning of "proxy"--which is a protocol term, not a file-related term.

@Robouste @ycmjason give that PR a test run and let me know if it solves your particular needs. If it does, let's move the conversation there and close this one. Cool? 😎 Thanks!

**Comment by BigBlueHat** [comment]
You can use `404.html` for this purpose now. See https://github.com/indexzero/http-server/issues/367#issuecomment-471541179
