### ISSUE TITLE
[OFF-Topic] Similar package but with EJS support

### ISSUE THREAD

**Issue by vpontin** [indexzero/http-server#372]
Hi! Sorry about this useless issue, but i'm a very noob node user, and i saw [this SO answer](https://stackoverflow.com/a/18147361/4836556) about EJS, a package which adds a php-like server-side syntax for node.

But when i searched about EJS docs most examples uses express, a sighly advanced framework for web apps.

So my question is: Is there any simple webserver like this one but with EJS-like syntax?

If not, do you plan to add any support for server-side scripting? Or is there any simple alternative for local developement (mostly about frontend, i dont want to worry much about server-side things).

Thanks in advance!

**Comment by BigBlueHat** [comment]
This project isn't likely to build in any pre-processing directly. It's meant for simple serving of static stuff. 😸 

You could, alternatively, pre-process (even via a watcher) the EJS templates into static files that `http-server` could then serve.

If you don't want to worry about server-side things, then `http-server`'s a great project, but if you need more advanced/configurable server-side dynamic scripting capabilities, I'd recommend digging into http://expressjs.com/ You can then build custom servers that match your needs.

Thanks for asking!
🎩
