### ISSUE TITLE
Is there any way to configure middleware

### ISSUE THREAD

**Issue by maximusk** [indexzero/http-server#373]
Hey, I really like the server for simplicity. But I need to configure my custom redirects through middleware. I haven't found any information about that. Is it supported?

**Comment by BigBlueHat** [comment]
There's no command line option for this, but you can do it by passing a `before` parameter to `createServer()` which gets added first before the internal middleware is added:
https://github.com/indexzero/http-server/blob/master/lib/http-server.js#L58-L66

Before is an array of middeware functions.

Cheers!

**Comment by maximusk** [comment]
thanks

> but you can do it by passing a before parameter to createServer() 

how can I do that? should I modify the sources?

**Comment by BigBlueHat** [comment]
No, you'd create a new JS script that wraps this code and calls `createServer()`. Alternatively, you could build directly off of [ecstatic](https://github.com/jfhbrook/node-ecstatic) (which `http-server` is based on).

`http-server` is focused on command line usage for serving static files, so doing something nifty with redirects currently requires using a different server or rolling your own--which will always be true if your needs are unique.

Regardless, there is some growing interest in rewrites, redirects, and header customization, so there will likely be a system for adding these sometime in the future.

Cheers!
