### ISSUE TITLE
Does this support http requests other than GET.

### ISSUE THREAD

**Issue by pkgodara** [indexzero/http-server#383]
Like http POST to upload file, DELETE to delete file on some binded ips? And others can only GET.

**Comment by pkgodara** [comment]
If yes, please give me an example. I want *.example.com domains to POST & DELETE. Anyone else can only GET.

**Comment by BigBlueHat** [comment]
Currently this is a `GET` only server--wrapping https://github.com/jfhbrook/node-ecstatic

If you want full-on read/write support, building up from something like http://expressjs.com/ is generally a better approach.
