### ISSUE TITLE
Windows cannot delete website folder even after stopping server

### ISSUE THREAD

**Issue by BaileyMillerSSI** [indexzero/http-server#384]
I created a script that launches the server via a batch file. If I use `ctrl+c` to close the server, I notice that I can still navigate to localhost and see the pages being served and that I cannot delete the website folder because they're in use.

Windows 10
Latest http-server

**Comment by BigBlueHat** [comment]
This is likely an issue with node and not with http-server itself. I've yet to see this issue myself (on Windows 10).

Has this continued to happen for you?

**Comment by BigBlueHat** [comment]
Also, what console are you using? PowerShell, `cmd`, the Linux subsystem, or mingw or something I've not yet heard of? 😺

**Comment by BaileyMillerSSI** [comment]
Yes this still happens, I am running this script from a .bat file into the command prompt. I have since changed the starting port though because I set the port to be the same as Angular 2 development port which is 4200 and they'd run at the same time occasionally.

**Comment by BigBlueHat** [comment]
@BaileyMillerSSI it's possible that calling it from the `.bat` file and/or tangling the port numbers with something else may have caused that issue.

However, I have just experienced the inverse scenario. See #391.

**Comment by BigBlueHat** [comment]
Pretty sure (as with #391) this isn't something we can solve...sadly...
