### ISSUE TITLE
why not add 'after' into serverOptions to as middleware list to handle with response?

### ISSUE THREAD

**Issue by Jeremyyang** [indexzero/http-server#388]
As a new Nodejser,  I read the code in `./lib/http-server.js`, I find that it creates httpserver through `[union](https://www.npmjs.com/package/union)`, who has already provided the option 'after' as its response middleware list. Then could http-server add it into to extend its response logging function?

//here is http-server.js code
`var serverOptions = {`
    `before: before,`
    `headers: this.headers,`
`    onError: function (err, req, res) {`
`      if (options.logFn) {`
`        options.logFn(req, res, err);`
      `}`
`      res.end();`
`    }`
`  };`
`  if (options.https) {`
    `serverOptions.https = options.https;`
`  }`
`  this.server = union.createServer(serverOptions);`

//here is union.RoutingStream code
`var RoutingStream = module.exports = function (options) {`
  `options = options || {};`
`  RequestStream.call(this, options);`
`  this.before = options.before || [];`
`  this.after = options.after || []; `
`  this.response = options.response || options.res;`
`  this.headers = options.headers || {`
`    'x-powered-by': 'union ' + union.version`
`  };`
`  this.target = new ResponseStream({`
`    response: this.response,`
 `   headers: this.headers`
 ` });`
`  this.once('pipe', this.route);`
`};`
Then it is an other question that how could I log the response info without 'after middleware'?

**Comment by thornjad** [comment]
As documented in #483, we're trying to get rid of the dependency on `union`, so for now, we don't need to spend the time improving usage of `union`, even though this is a good point. Thank you!
