### ISSUE TITLE
New Relic Integration

### ISSUE THREAD

**Issue by priyabg** [indexzero/http-server#389]
We have been using http-server as a nodejs based web server to serve our angular spa.
Our devops team want to enable New Relic APM for the frontend webserver. 
I am still trying to understand prerequisites for doing this. As per my understanding I have to make changes in http-server to hook New Relic APM. 
Could you please help me and steer me in the right direction.
Below is the link to New Relic APM.
https://docs.newrelic.com/docs/agents/nodejs-agent/installation-configuration/install-nodejs-agent

**Comment by BigBlueHat** [comment]
You would indeed need to make a variation of the command line node.js app:
https://github.com/indexzero/http-server/blob/master/bin/http-server#L123

It shouldn't be much/any harder than adding the New Relic `require()` statement--as per the docs you linked to. However, your mileage is certain to vary. 😃 

Hope that helps!

**Comment by BigBlueHat** [comment]
Closing this as out of scope. Hope you got it sorted out, though!
