### ISSUE TITLE
How can I add a `prefix` for public path?

### ISSUE THREAD

**Issue by gejiawen** [indexzero/http-server#390]
Hi there,

I want to run a `http-server` instance with a prefix access.

For example,

```shell
$ hs some_folder --prefix /handbook
```

After that, I can access by `http://localhost:8080/handbook` to view the `some_folder`.

How to get this usage?

**Comment by BigBlueHat** [comment]
Do you have another server listening on that port?

If not, then simplest thing would be to rename `some_folder` to `handbook` and run `http-server` in the parent directory.

**Comment by gejiawen** [comment]
@BigBlueHat 

Yeah, I know that. 
I just want to know if `http-server` support a `prefix` configuration. It's seem to do not support.
