### ISSUE TITLE
"Permission denied" when deleting a (large) file being served

### ISSUE THREAD

**Issue by BigBlueHat** [indexzero/http-server#391]
Perhaps not directly related to #384, but it is afaik Windows 10 related.

I can't remove a (large audio) file while `http-server` is serving it. Presumably that's due to some locking that happens during the streaming/reading process. Once I killed `http-server` all was well again.

I'm curious if others have this same issue on other platforms.

**Comment by Raindeer44** [comment]
I'm not getting the same on Linux Mint 18.2. My first guess would also be a locking mechanism, possibly just on Windows.

**Comment by BigBlueHat** [comment]
Pretty sure this isn't actually something we can solve...sadly...
