### ISSUE TITLE
ctrl - c does not truly shutdown http-server (Cygwin)

### ISSUE THREAD

**Issue by jrtobac** [indexzero/http-server#393]
I am on step 0 of the phonecat app tutorial.
I am on Windows 10, and using a cygwin console.

When I run npm start, 
package.json:

> ...
> "start": "http-server ./app -a localhost -p 8000 -c-1",
> ...

the app starts fine, and I can see the generated angular website at http://localhost:8000/index.html.
My console prompts me to hit ctrl-c to stop the server.

When I hit ctrl-c the server appears to stop and my console returns to its normal screen.
I even run `ps aux` to be sure that everything stopped running.

However, if I navigate back to http://localhost:8000/index.html, I am still able to see the website, and cygwin displays messages as though the server is still running.

Messages from cygwin console:

> $ npm start
> 
> > angular-phonecat@0.0.0 prestart C:\cygwin64\home\User\angular-phonecat
> > npm install
> 
> 
> > angular-phonecat@0.0.0 postinstall C:\cygwin64\home\User\angular-phonecat
> > bower install
> 
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
> 
> > angular-phonecat@0.0.0 start C:\cygwin64\home\User\angular-phonecat
> > http-server ./app -a localhost -p 8000 -c-1
> 
> Starting up http-server, serving ./app
> Available on:
>   http://localhost:8000
>   Hit CTRL-C to stop the server

This is where I hit ctrl-C and the console returns to normal until I navigate to the website again and I get:

> User@DESKTOP-MTQB35F ~/angular-phonecat
> $ [Thu Aug 24 2017 01:28:20 GMT-0400 (Eastern Daylight Time)] "GET /index.html" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.101 Safari/537.36"
> [Thu Aug 24 2017 01:28:20 GMT-0400 (Eastern Daylight Time)] "GET /bower_components/bootstrap/dist/css/bootstrap.css" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.101 Safari/537.36"
> [Thu Aug 24 2017 01:28:20 GMT-0400 (Eastern Daylight Time)] "GET /bower_components/angular/angular.js" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.101 Safari/537.36"

The only way that I have been able to effectively shutdown the server is by starting the task manager and stopping cygwin from running.

Why is this happening and how can I successfully shutdown http-server without having to kill cygwin entirely?

**Comment by BigBlueHat** [comment]
I sadly don't use cygwin, but I do use [mingw](http://mingw.org/) (via the [git](https://git-scm.com/)) and have never had this problem.

Perhaps it's a cygwin issue?

**Comment by BigBlueHat** [comment]
So. I now have this problem...in mingw...on Windows 10...running Node 8.6.0. 😕 

This seems to be an old issue (actually) #183, but given its "random" nature...I'm not sure where to start.

I'm going to close this in favor of #183. Feel free to report any future findings there. Thanks!
