### ISSUE TITLE
Migrating code to ES6

### ISSUE THREAD

**Issue by itaditya** [indexzero/http-server#397]
Hey there I really want to contribute to such a useful CLI tool. One of which would be to migrate the code to ES6.

For your comparison, consider this snippet from the project -

```js
Object.keys(ifaces).forEach(function (dev) {
    ifaces[dev].forEach(function (details) {
        if (details.family === 'IPv4') {
            logger.info(('  ' + protocol + details.address + ':' + colors.green(port.toString())));
        }
    });
});
```
```js
Object.keys(ifaces).forEach(dev => ifaces[dev].forEach(details => {
    if (details.family === 'IPv4') {
        logger.info(`${protocol}${details.address}:${colors.green(port.toString())}`);
    }
}));

```

**Comment by BigBlueHat** [comment]
Thanks for asking @itaditya! I think at this point a wholesale migration to ES6 would not benefit the quality or stability of the project. If/when there's an ES6 feature that would greatly enable something we need here (either a fix or a feature), then I'd be supportive of the move. For now, though, I'm not sure a wholesale switch would be worth the risk.

Thanks again for asking, though!
🎩

**Comment by itaditya** [comment]
@BigBlueHat thanks for replying, I just want to know why do you think the quality wouldn't improve?
