### ISSUE TITLE
how to deploy this project In IIS

### ISSUE THREAD

**Issue by addikhann** [indexzero/http-server#398]
how to run this project In IIS

**Comment by BigBlueHat** [comment]
Actually, you would run this project *instead* of IIS. It will listen on port `8080` by default. If IIS is already listening on that port, you can run http-server like `http-server . -p 8090` (or whatever).

If you have more specific errors, feel free to reopen this issue or file new ones.

Thanks!
🎩

**Comment by addikhann** [comment]
i want run this project in IIS , locally its working fine ,but I want to deploy my Web application in IIS, it's not working properly I am searching 3 to hours but doesn't success.
how to work this project on IIS. if you need anything else for understand I am here. I share Two images for you understand my problem

 ```
var app = angular.module('app', ['ui.router', 'ui.bootstrap', 'flash',
        //main modules
        'login', 'dashboard','staffregistration']);


    app.config(['$stateProvider', '$locationProvider', '$urlRouterProvider', function ($stateProvider, $locationProvider, $urlRouterProvider, $modalInstance) {

        //IdleScreenList
        $stateProvider
           .state('app', {
               url: '/app',
               templateUrl: 'app/common/app.html',
               controller: 'appCtrl',
               controllerAs: 'vm',
               data: {
                   pageTitle: 'Login'
               }
           });

        $urlRouterProvider.otherwise('login');

        //$urlRouterProvider.otherwise('app/dashboard');
        //$urlRouterProvider.otherwise('/app/dashboard');
    }]);

    // set global configuration of application and it can be accessed by injecting appSettings in any modules
    app.constant('appSettings', appConfig);

```
webconfig
```
 <configuration>
     <system.webServer>
        <defaultDocument>
          <files>
            <clear />
            <add value="index.html" />
          </files>
        </defaultDocument>
    </system.webServer>
    </configuration>
```
https://stackoverflow.com/questions/46336656/simple-angularjs-application-run-iis?noredirect=1#comment79643331_46336656
https://i.stack.imgur.com/KyI1u.jpg
