### ISSUE TITLE
Suggest: max-age=0 or no Cache-Control header by default

### ISSUE THREAD

**Issue by k8w** [indexzero/http-server#407]
1. It is what `express` and `nginx` do
2. If user forget `-c-1`, and visited a page by mobile phone, they must restart `http-server` and manually clean phone cache. (I always forget this, almost use `http-server` as local dev server)

**Comment by BigBlueHat** [comment]
I too often forget the `-c-1` bit. However, I think changing this default would at least mean we'd need a major point release to avoid breaking deployments that depend on the current defaults.

**Comment by k8w** [comment]
Or maybe , add something like global config ?

**Comment by BigBlueHat** [comment]
Yeah...I keep pondering this also. Our current "tagline" though is "a simple zero-configuration command-line http server."

Perhaps if file-based configuration is available, but not the default, we can have both things in one package.

Pondering. 😃

**Comment by rjsteinert** [comment]
There is a lot `hs -c-1` out there for people starting with `hs`, figuring that out is a gotcha. If over 50% of folks use `hs` in situations that justify caching, then great, leave as is. I've personally never seen any use of `hs` where caching was justified, thus caching on does not seem like a "sensible default".

**Comment by rjsteinert** [comment]
Also, on the topic of sensible defaults, I vote that `hs` should be packaged with node similar to how npm is packaged with node.

**Comment by BigBlueHat** [comment]
The problem is less about what a "sensible default" might have been when this was put into place, but what the cost of changing a default is going forward.

The risk with flipping a default is that you'll break every deployment that depends on that default--which is bad. ☹️

So, it's unlikely that this default will change.

A README update to make the `-c-1` option more obvious would be great, though. 😁

**Comment by BigBlueHat** [comment]
If any of you have ideas on how to not break existing deployments that may be simply running with all the defaults (i.e. `http-server .`), I'm all :ear:'s.

Right now, though, I can't see how to do it without causing as much pain as benefit. Sadly.

**Comment by rjsteinert** [comment]
Fair points @BigBlueHat - I'll switch to serve for now https://github.com/zeit/serve
