### ISSUE TITLE
http cache work not correct?

### ISSUE THREAD

**Issue by mrdulin** [indexzero/http-server#412]
1. First build, deploy and access `about` page, http status code is 304, that's fine.

![1](https://ws4.sinaimg.cn/large/006tNc79gy1fmebzlxwvyj31an07y751.jpg)

2. modify `about` page code, build, only the `about` page filename hash is changed.  `vendor` filename is not changed, So, I expect `vendor` file should use http cache, **should not send a http request again**.

3. but, when I second build, deploy and access `about`page, the `vendor` file send a new http request.

![](https://ws3.sinaimg.cn/large/006tNc79gy1fmec0g6v3qj31aj08iq3p.jpg)

**Comment by Nostradamos** [comment]
I have the same problem, seems like the http-server sends a 304.

**Comment by everdrone** [comment]
same problem, even after firing `http-server` again `*.css` files are not updated

**Comment by mrdulin** [comment]
@Nostradamos @everdrone I find the answer. In my case, the reason is `max-age` duration is too short. After I modify, compile, build and start the server again. The  resources are already expired. 
That's why browser `send a new resource request with resource entity`(status code = 200), not `send a request header` for check the resource freshness(status code = 304) .
