### ISSUE TITLE
Supported way to prompt for actual port

### ISSUE THREAD

**Issue by alexfmpe** [indexzero/http-server#413]
`http-server` is being used in https://github.com/krausest/js-framework-benchmark/.
When `portfinder` picks a port different from 8080, we need to pass that port to selenium https://github.com/krausest/js-framework-benchmark/issues/333.

At the moment I'm getting by with
 `grep "127.0.0.1" server.out | sed -e 's/.*127.0.0.1://'`

Is there currently a better way ? 
If not, how about outputting a .json file with address/port/etc ?
I could open a PR, if this is desired.

**Comment by BigBlueHat** [comment]
What you're doing now seems like the best solution. I'm not keen on use outputing JSON-files for data that can (and is) already logged to stdout.

I would be fine with you adding that grep + sed command to the README though. 😃
