### ISSUE TITLE
Vulnerability in mime dependency

### ISSUE THREAD

**Issue by naugtur** [indexzero/http-server#419]
nsp check
(+) 1 vulnerabilities found

|  | Regular Expression Denial of Service     |
| --- | --- |                                                                                 
| Name          | mime                                                                                                                     |
| CVSS          | 7.5 (High)                                                                                                               |
| Installed     | 1.3.6                                                                                                                    |
| Vulnerable    | < 1.4.1 | > 2.0.0 < 2.0.3                                                                                 |               
| Patched       | >= 1.4.1 < 2.0.0 | >= 2.0.3                                                                           |                   
| Path          |  http-server@0.10.0 > ecstatic@2.2.1 > mime@1.3.6    |                                              
| More Info     | https://nodesecurity.io/advisories/535                            |

**Comment by BigBlueHat** [comment]
Huge thanks for reporting this! I'm finishing up the bits to ship this to NPM.

**Comment by naugtur** [comment]
No problem. Thanks for all the great work!
