### ISSUE TITLE
I cannot get .woff or .woff2 font files in the server

### ISSUE THREAD

**Issue by zhongshan1993** [indexzero/http-server#422]
404 Not Found Error with .woff or .woff2 Font Files
Is there a solution for this?

**Comment by BigBlueHat** [comment]
Strange. Are the fonts you're using open source? If so, could you add them to the `public/` folder with a demo page an send a PR? I'd be happy to a) take a look and b) merge the example if it seems broadly useful.

Cheers!

**Comment by zhongshan1993** [comment]
I am so sorry. Maybe it's my fault, it works well tody.
