### ISSUE TITLE
forward push-state requests to index.html

### ISSUE THREAD

**Issue by ORESoftware** [indexzero/http-server#427]
We are experiencing this issue:

https://stackoverflow.com/questions/31415052/angular-2-0-router-not-working-on-reloading-the-browser

It has to do with push-state. It looks like our http-server is getting requests to /foo or /bar, but we need those requests to be mapped to index.html.

Is there a way to map all routes in index.html?

with the `live-server` package, it apparently looks like this:

> using live-server: https://www.npmjs.com/package/live-server
> ```bash
> $ live-server --entry-file=index.html
> ```
>

**Comment by ORESoftware** [comment]
My guess is that proxy option can do what we want? something like this:

-P or --proxy Proxies all requests which can't be resolved locally to the given url. e.g.: -P http://someurl.com

so:

`http-server . --proxy index.html`

**Comment by BigBlueHat** [comment]
Requiring JavaScript to resolve server-focused URLs is an anti-pattern (however popular). Be sure all non-hash fragment URLs have their own server-side representation or use hash URLs.

If you need that feature, I'd stick with `live-server` as `http-server` is focused on HTTP serving. Thanks!
