### ISSUE TITLE
How add mime-type?

### ISSUE THREAD

**Issue by aasci** [indexzero/http-server#429]
Hi, i am developing an application with http-vue-loader, but the server do not knows "vue" file.
es.
new Vue({
        el: '#my-app',
        components: {
          'my-component': httpVueLoader('my-component.vue')
        }
});

The file my-component.vue is in the root of the server, but the il server response with 404.
Thanks.

**Comment by BigBlueHat** [comment]
Sending a file with an incorrect media type wouldn't trigger a 404, so something else is wrong. At most, it would return a [416 Not Acceptable](https://tools.ietf.org/html/rfc7231#section-6.5.6). The `Content-Type` returned is `application/octet-stream; charset=utf-8` and, in this case, http-vue-loader doesn't care (and parse it with the assumption it's supposed to be a Vue component) and will work as long as the relative URL is correct.

A local test using the simple example from https://github.com/FranckFreiburger/http-vue-loader#examples worked fine for me locally.

Make sure your URLs/paths all point to the right things, and you should be fine.

Cheers!
