### ISSUE TITLE
Docs bug - disable caching value

### ISSUE THREAD

**Issue by ORESoftware** [indexzero/http-server#430]
I see this:

`-c-1`

shouldn't it be this?

`-c -1`

with an extra space between the c and the second `-` sign?

**Comment by coderkd10** [comment]
`-c-1 ` works (I have personally used it on numerous occasions).

**Comment by ORESoftware** [comment]
yes, it seems to, but `-c-1` is also bizarre/unfamiliar syntax lol

**Comment by BigBlueHat** [comment]
The options parser handles both, and putting the space in made it unclear (to me) if `-1` is a value or a separate option--hence the lack of a space. 😄 

Anyhow. Since it works, this isn't a bug, but thanks for caring!

**Comment by ORESoftware** [comment]
Not that this matters, but personally not a fan `--no-cache` would have been just fine lol

`-c=0` would also have been fine lol

lol
