### ISSUE TITLE
Automatically create self-signed cert?

### ISSUE THREAD

**Issue by laggingreflex** [indexzero/http-server#431]
Would it be a good idea to create self-signed certificate to be used when enabling https? Using something like [selfsigned](https://github.com/jfromaniello/selfsigned) or [https-pem](https://github.com/watson/https-pem)

**Comment by BigBlueHat** [comment]
#402 is similar and references how to make one using `openssl` on the command line.

Do you know of any self signed cert tools that work in a similar command line fashion as openssl?

I'd be 👍 on including one as a dev dependency, but I'm not keen to make managing cert creation part of this project (trying to avoid scope creep).

**Comment by AJLoveChina** [comment]
For automatically  self-signed cert
you can try this : https://github.com/AJLoveChina/http-server-v2

@laggingreflex
