### ISSUE TITLE
CORS headers are sent in lowercase and thus not registered by Firefox

### ISSUE THREAD

**Issue by hoschiCZ** [indexzero/http-server#432]
```
$ http-server --cors # another terminal tab
$ telnet localhost 8080
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
GET /emptyfile.txt

HTTP/1.1 200 OK
access-control-allow-origin: *
access-control-allow-headers: Origin, X-Requested-With, Content-Type, Accept, Range, *
server: ecstatic-1.4.1
last-modified: Sat, 24 Feb 2018 15:28:05 GMT
etag: "7211906-0-"2018-02-24T15:28:05.702Z""
cache-control: max-age=3600
content-length: 0
content-type: text/plain; charset=UTF-8
Date: Sat, 24 Feb 2018 15:28:12 GMT
Connection: close

Connection closed by foreign host.
```

As you can see, http-server sends the access-control-allow-origin headers in lowercase. According to the spec, they should be spelled like this: "Access-Control-Allow-Origin".

This non-standards-compliant behaviour on http-server's side, as proven by the telnet excerpt, causes Firefox to not take the `--cors` option into account. On an app, hosted by http-server, Firefox reports: (Report: CORS header 'Access-Control-Allow-Origin' missing). Chrome goes by just fine.

I would expect http-server to send the headers in the correct casing.

Thanks

**Comment by BigBlueHat** [comment]
HTTP headers are case-insensitive and have been since RFC2616: https://stackoverflow.com/a/5259004/507169

So, http-server (and the underlying node-ecstatic) are standards compliant.

Likely something else is causing this error to be thrown and not http-server.
