### ISSUE TITLE
how to display File/Dir last modification time

### ISSUE THREAD

**Issue by esmeetu** [indexzero/http-server#433]
I want to see the files' time changes on the server, any suggestions?
Like this:

Name | Size | Date Modified
-- | -- | --
test |  10k  | 25/02/2018, 00:00:00

**Comment by BigBlueHat** [comment]
@esmeetu do you mean present the last modified date within the response to a request?

Anything that modifies the request content would amount to Server-Side Rendering (SSR), which is not what this project does.

However, you will find size and last modified date already present in the HTTP headers of every request:
```http
< HTTP/1.1 200 OK
< server: ecstatic-2.2.1
< last-modified: Mon, 26 Feb 2018 15:40:31 GMT
< etag: "4785074604599411-144-"2018-02-26T15:40:31.546Z""
< cache-control: max-age=-1
< content-length: 144
< content-type: text/html; charset=UTF-8
< Date: Tue, 27 Feb 2018 16:27:00 GMT
< Connection: keep-alive
```

[Content-Length](https://tools.ietf.org/html/rfc7230#section-3.3.2) is the size. [Last-Modified](https://tools.ietf.org/html/rfc7232#section-2.2) is the...last modified date. [Date](http://webconcepts.info/concepts/http-header/Date) is the date of the request.

You can access these per-resource via JavaScript (if you want) by doing a HEAD request on each URL.

Hope that helps!
