### ISSUE TITLE
localhost vs. 127.0.0.1

### ISSUE THREAD

**Issue by BugsBunny338** [indexzero/http-server#443]
When I use option `-a localhost`, it still only serves by default on `127.0.0.1`, but not on `localhost`.

**Comment by BigBlueHat** [comment]
You shouldn't have to use `-a localhost` as `http-server .` will serve on both--unless you've mapped `localhost` to something else via your `/etc/hosts` (or equivalent) file.

**Comment by BugsBunny338** [comment]
Haven't mapped `localhost` to anything else, haven't messed with a `hosts` file either. No special settings that I'm aware of. Tried with different browsers (Chrome, Safari, Firefox, ...). Server simply runs fine on `127.0.0.1:8080`, but is not accessible on `localhost:8080`. Any ideas?

**Comment by BigBlueHat** [comment]
Really sorry this is happening, but I'm confident it's beyond the scope of this project to address--it's something broken in your local machine settings...somewhere. 😢 

Hope you find the fix!
