### ISSUE TITLE
brotli support

### ISSUE THREAD

**Issue by mendrik** [indexzero/http-server#445]
Would be a nice to have, like --gzip

[Brotli](https://github.com/google/brotli)

**Comment by BigBlueHat** [comment]
Definitely open to PRs for this one. 😄

**Comment by thornjad** [comment]
This is definitely needed! I've just started working on adding brotli support in the upstream project ecstatic first, and I'll open a PR here once ecstatic releases it. My thought is to be able to pass it just like gzip, i.e. `http-server --brotli`

**Comment by thornjad** [comment]
See jfhbrook/node-ecstatic#228
