### ISSUE TITLE
When I run http-server command, there are four available ip address.

### ISSUE THREAD

**Issue by mrdulin** [indexzero/http-server#455]
```bash
☁  nodejs-graphql [master] http-server
Starting up http-server, serving ./
Available on:
  http://127.0.0.1:8080
  http://172.31.160.114:8080
  http://192.168.99.1:8080
  http://10.27.112.37:8080
Hit CTRL-C to stop the server
```

http://127.0.0.1:8080 and http://172.31.160.114:8080 can be accessed by browser.

http://192.168.99.1:8080 and http://10.27.112.37:8080 can **not** be accessed by browser.

I know 127.0.0.1 ip address is localhost, and 172.31.160.114 is wifi network ip address. 
What are the other two?

**Comment by BigBlueHat** [comment]
Those other two are internal network only ranges: https://www.lifewire.com/what-is-a-private-ip-address-2625970

It looks like `http-server` is discovering them (and listening on ports there), but something in your firewall (maybe?) setting is preventing the browser from seeing them.

Not sure what's causing it, but not sure it's a bug either. Thoughts?

**Comment by thornjad** [comment]
@mrdulin what OS are you using, and do you have any firewall rules that might be blocking those? That's the only problem I can think of.

**Comment by mrdulin** [comment]
@BigBlueHat Yeah. It's not a bug. Just curious. thanks for reply

@thornjad MacOS, I found this in company, so I think there are firewall rules no doubt.  I am not a professional network engineer. Just curious. thanks for reply
