### ISSUE TITLE
support --port

### ISSUE THREAD

**Issue by johnstonmatt** [indexzero/http-server#466]
`-p` flag works, but long form --port should work too. Its a non-breaking change, trivially easy, and makes things more declaritive. I can make a PR if @indexzero gives it a green light?

**Comment by BigBlueHat** [comment]
Send along that PR @johnstonmatt. Thanks!

**Comment by johnstonmatt** [comment]
hey all, this PR failed on travis, but I believe that was not a result of the change. Is this good to be merged?

**Comment by NightMachinary** [comment]
I installed the latest version just now, and --port still doesn't work and doesn't produce an error message either.

**Comment by thornjad** [comment]
@NightMachinary what was the exact command you used and what was the output?

**Comment by webdesignberlin** [comment]
Usage of
`npx http-server ./dist --port 5454`

start server but only with default port 8080:
`npx: Installierte 26 in 2.235s
Starting up http-server, serving ./dist
Available on:
  http://127.0.0.1:8080
  http://10.100.179.79:8080
Hit CTRL-C to stop the server`
