### ISSUE TITLE
Server responding with 404 even though having br extension

### ISSUE THREAD

**Issue by Biboswan** [indexzero/http-server#469]
Files with gzip extension works with `http-server -g ` but  `http-server -b` or `http-server --brotli` is not working with br extension.
Node version: 10.6.0
Browser (chrome canary) sends br as an option in request header.

**Comment by BigBlueHat** [comment]
@Biboswan we haven't yet merged #465. Please give that branch a look, try it, review the code, etc. I would like to get that into the next minor point release if everything checks out.

Cheers!
🎩
