### ISSUE TITLE
Add basic auth

### ISSUE THREAD

**Issue by jondlm** [indexzero/http-server#47]
It would be nice if we could specify `--user` and `--pass` to require basic authentication for the server. Obviously this shouldn't be considered secure, but it would be a nice feature for basic protection.

**Comment by jhnns** [comment]
I was also looking for that :+1:. It's good in situations where you need to simulate a basic auth environment.

**Comment by jondlm** [comment]
I wrote a PR for this but it's really outdated and was never merged. I believe it wasn't too hard to implement, but I probably won't have time to bring it up to date any time soon.

**Comment by WANG-lp** [comment]
This is what I want! Pls add this feature ASAP.  :+1:

**Comment by brandonros** [comment]
Why is this not merged?...

**Comment by christianbundy** [comment]
@brandonros 

I assume that you mean #245, but since there hasn't been a merge in months (ref #319) I don't expect it to be merged any time soon.

**Comment by BigBlueHat** [comment]
Closing this in favor of putting the focus on #245 as the discussion point. Planning to get Basic Auth into v0.10.0. Cheers!
