### ISSUE TITLE
Feature: add delay to responses (ms)

### ISSUE THREAD

**Issue by balalaXD** [indexzero/http-server#476]
Sometimes i want to test loading-spinner UI, but the responses is too fast to see the spinner animation

Add command line options:   
--delay, -d     Add delay to responses (ms)

**Comment by BigBlueHat** [comment]
@balalaXD probably best to use a different thing to inject the delay. It would be far too easy to get this feature confused with something else and cause problems--especially for folks using `http-server` in production.

Great idea in general, but probably not the best project to implement it.

**Comment by aadrian** [comment]
@BigBlueHat a delay would totaly belong to the functionality of a simple http-server. This project https://www.npmjs.com/package/http-live-simulator  serves the same niche as `http-server` and has that delay implemented.
