### ISSUE TITLE
Add support for Let's Encrypt

### ISSUE THREAD

**Issue by snowdream** [indexzero/http-server#489]
like this: https://git.coolaj86.com/coolaj86/greenlock.js

**Comment by thornjad** [comment]
Are you suggesting this as a way to generate TLS certificates on the fly? If so, I think this may be out of scope for this project.

**Comment by BigBlueHat** [comment]
This has come up occasionally here. @snowdream if you'd like to add to the README for how this can be done via Greenlock.js that'd be super! It's just not likely something we'd mix directly into the project.
