### ISSUE TITLE
Add issue and pull request templates

### ISSUE THREAD

**Issue by thornjad** [indexzero/http-server#500]
High quality issue and pull request templates help everyone! The templates are only guidelines and don't need to be highly sophisticated, but nudging submissions towards more info is always good. I know I need the nudging!

A couple thoughts:

- In issues reporting a bug, its helpful to have the `http-server` version and also the complete error and/or stack trace if applicable.
- Pull requests should be made against the `master` branch only
- Pull requests should explain what changes were made and why, unless its obvious.

**Comment by amad-person** [comment]
Would like to take this issue up!

**Comment by thornjad** [comment]
Perfect! Yeah those sample templates look pretty good. I haven't come across that repo before, good find!

**Comment by amad-person** [comment]
Proposed issue template:

```
**Do you want to request a *feature* or report a *bug*?**

**If the issue is a bug report, please provide the steps to reproduce it. Please include the actual source code causing the issue if applicable.**

<!-- Paste the source code here: -->

**What did you expect to happen?**

**What actually happened? Please include the actual error trace and / or stack trace if applicable.**

<!-- Paste the error and / or stack trace here: -->

**If the issue is a feature request, what is the motivation / use case for it?**

**Tell us about your environment**
- **http-server version:**
- **Platform:**

**Other information (related issues, suggestions for a fix, etc):**
```

Proposed PR template:

```
* **Please ensure that your PR fulfills these requirements:**
- [ ] The pull request is being made against the `master` branch
- [ ] Tests for the changes have been added (for bug fixes / features)

**What is the purpose of this pull request? (bug fix, enhancement / feature)**

<!--
    If this pull request is addressing an issue, link to the issue here: "Fixes #xxx" or "Resolves #xxx"
-->

**What changes did you make?**

**Provide some example code that this change will affect, if applicable:**

<!-- Paste the example code here: -->

**Is there anything you'd like reviewers to focus on?**

**Please provide testing instructions, if applicable:**
```

**Comment by thornjad** [comment]
That looks good! My only note is that `http-server` is meant to be a CLI tool, so there probably won't be any source code to include most of the time. Instead, we could ask for the exact command used and/or the full output in the terminal.

But it looks good! Go ahead an submit a PR if you'd like!
