### ISSUE TITLE
Cannot install! Unexpected end of JSON input

### ISSUE THREAD

**Issue by DininduWanniarachchi** [indexzero/http-server#508]
**Cannot install!**

**I keep getting bellow error while trying to install.**

```
npm install http-server -g

npm ERR! Unexpected end of JSON input while parsing near '...5f772c783","tarball":'

```
- **http-server version: latest**
- **Platform: windows 10 (x64)**

**Comment by BigBlueHat** [comment]
@DininduWanniarachchi that's likely a network issue, and not a packaging issue. I just successfully installed on Windows 10 with no issues.

Try again (if you would) and reopen this if you're sure it's something we can solve here.

Thanks!
🎩

**Comment by dinindu-live** [comment]
Still not working,

![image](https://user-images.githubusercontent.com/49564155/56354870-7d14b600-61f2-11e9-9c5a-df5e40ab0e1f.png)

**Comment by thornjad** [comment]
Try running

```
npm uninstall -g http-server
npm cache clean --force
npm install -g http-server
```

If that doesn't work, maybe try

```
npm install -g npm
```

This is 100% an npm issue, though we're happy to try to help!
