### ISSUE TITLE
Is http-server is HTTP server or HTTP GET server?

### ISSUE THREAD

**Issue by PavelSosin** [indexzero/http-server#533]
**Do you want to request a *feature* or report a *bug*?**
**Feature.** 
HTTP means not only GET. If so it shall be called **static-http-server**
**If the issue is a bug report, please provide the steps to reproduce it. Please include the actual command causing the issue if applicable.**

**What did you expect to happen?**

**What actually happened? Please include the actual error trace and / or stack trace if applicable.**

**If the issue is a feature request, what is the motivation / use case for it?**

**Tell us about your environment**
- **http-server version:**
- **Platform:**

**Other information (related issues, suggestions for a fix, etc):**

**Comment by thornjad** [comment]
Renaming a project is not trivial. Besides, static-http-server [already exists](https://www.npmjs.com/package/static-http-server)
