### ISSUE TITLE
"History Mode" of Vue.js

### ISSUE THREAD

**Issue by lacivert** [indexzero/http-server#542]
**Do you want to request a *feature* or report a *bug*?**
feature

**If the issue is a feature request, what is the motivation / use case for it?**
Vuejs has a "history mode"
https://router.vuejs.org/guide/essentials/history-mode.html#example-server-configurations

There are some config for the servers like Apache. But I don't know how to implement it for http-server. If there is a way to do that, I would like to know. If not, this can be a feature request.

**Tell us about your environment**
- **http-server version:**
- **Platform:** Mac OS X

**Comment by thornjad** [comment]
Is this the same as #318?

**Comment by lacivert** [comment]
@thornjad Thank you very much. I saw `serve` project with rewrite rules and it worked!

For those who is interested;

`serve.json`:

```
{
  "rewrites": [{
    "source": "**",
    "destination": "/index.html"
  }]
}
```

and;
`npx serve`

**Comment by favoyang** [comment]
Shortcut: `-s`  rewrite all not-found requests to `index.html`
```
serve -s PATH
```
