### ISSUE TITLE
gzip support

### ISSUE THREAD

**Issue by WickyNilliams** [indexzero/http-server#56]
Would it be possible to have an option for gzip/deflate compression?

**Comment by daliwali** [comment]
+1

**Comment by chadxz** [comment]
+1 would like this too

**Comment by hungsu** [comment]
+1 This sure would be sweet!

**Comment by llambda** [comment]
+1

**Comment by KyleAMathews** [comment]
+1

**Comment by mathiasschopmans** [comment]
:+1:

**Comment by LukeAskew** [comment]
+1

**Comment by Tims101** [comment]
:+1:

**Comment by michael-lawrence** [comment]
:+1:

**Comment by axwell** [comment]
No news on this ?

**Comment by avesus** [comment]
:+1:

**Comment by smarts** [comment]
I got this working locally (as an always-on feature, not configurable) by modifying http-server.js:
```javascript
  before.push(ecstatic({
    gzip: true, // HACK: I ADDED THIS LINE!
    root: this.root,
    cache: this.cache,
    showDir: this.showDir,
    autoIndex: this.autoIndex,
    defaultExt: this.ext,
    handleError: typeof options.proxy !== 'string'
  }));
```

**Comment by mydearxym** [comment]
+10

**Comment by hanai** [comment]
It't really useful.

**Comment by tomkel** [comment]
+1!

**Comment by bheiskell** [comment]
+1

**Comment by derhuerst** [comment]
Please use the [reaction feature](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments) to express you'd like to have this feature.

**Comment by gdi2290** [comment]
+1

**Comment by mattlavallee** [comment]
doing an npm install of http-server doesn't seem to pull in the gzip property event after an npm cache clean.  Is this feature available in the npm package yet?

**Comment by derhuerst** [comment]
> Is this feature available in the npm package yet?

Nope. `npm info http-server gitHead` says the published git commit is `1a8552c5e028bd5500027ee940111133927a4e94`. 1a8552c is behind b456b77, which added gzip support.

**Comment by golopot** [comment]
For what I understand the current --gzip option requires you to produce `something.ext.gz` by yourself. But what I want is a option that does the compression on the fly, like the express middleware `app.use(compress())`, just plug in one line and no hassle.

**Comment by BigBlueHat** [comment]
@golopot right now, I'd say that on-the-fly compression is "out of scope" for a static web server--which should really just transmit content with minimal involvement. If you'd still like to discuss it, though, please file a separate issue. Thanks!

**Comment by WickyNilliams** [comment]
To be clear, on-the-fly compression was exactly what I wanted when i originally opened this issue

**Comment by BigBlueHat** [comment]
Good to know @WickyNilliams. At this point, I don't plan on going beyond what's "underneath" in the form of `node-ecstatic`'s support https://github.com/jfhbrook/node-ecstatic#optsgzip

There are few things we're adding here, but mostly I'm wanting to continue to build up from the node-ecstatic foundation. Any sort of server-side content processing would be out-of-scope in that case.

**Comment by smarts** [comment]
@BigBlueHat i wasn't necessarily looking for on-the-fly compression. As noted in my previous comment
https://github.com/indexzero/http-server/issues/56#issuecomment-141689367
i got it working w/ a hack, but i'd like this to be supported by the server's options instead of having to hack it myself. Can it be added as an option?

**Comment by BigBlueHat** [comment]
@smarts it's been an option since 0.10.0 was released https://github.com/indexzero/http-server/releases/tag/0.10.0 😄 If you need something more, perhaps open a new issue so we can discuss that there rather than on this closed issue.

**Comment by smarts** [comment]
Doh! I now see the pull request that references this issue. Thanks for being patient w/ me @BigBlueHat 😅

**Comment by Viyozc** [comment]
+100

**Comment by Nashorn** [comment]
Seriously, don't understand how hard on-the-fly compression can be, in just a few lines:

var zlib = require('zlib');

pathName = url.parse(request.url).pathname;
var fp = __dirname+"/../.."+pathName; //custom patthing, ignore
  


  var readStream = fs.createReadStream(fp);
  readStream.on('open', function (res) {
    response.writeHead(200, { 'content-encoding': 'gzip' });
    readStream.pipe(zlib.createGzip()).pipe(response);
  });

**Comment by thornjad** [comment]
@Nashorn you're more than welcome to turn your suggestion into a pull request!

**Comment by Nashorn** [comment]
It's not clean from looking at http-server.js where i would integrate the above solution which does dynamic gzip compression on responses. I found this area, but not even sure where/how to plug in:

```
var serverOptions = {
    before: before,
    headers: this.headers,
    onError: function (err, req, res) {
      if (options.logFn) {
        options.logFn(req, res, err);
      }

      res.end();
    }
  };
```
