### ISSUE TITLE
How to monitor http-server

### ISSUE THREAD

**Issue by RickFrom1987** [indexzero/http-server#66]
Going to try to use http-server for production static site. Would be nice if there was some docs on how to use monit or forever to keep this service up. Any hints or tips for some sort of monitoring would be really helpful for me!!! Thanks Awesome project.

**Comment by indexzero** [comment]
@RickFrom1987 using `forever` is pretty straight forward:

```
npm i -g forever http-server
forever start `which http-server` -p 8000 -d true -e html
```

where `-p 8000 -d true -e html` are just some example `http-server` options.
