### ISSUE TITLE
Show /404.html on 404

### ISSUE THREAD

**Issue by jfhbrook** [indexzero/http-server#7]
The place to add this to the vendored node-static is probably somewhere in here:

```
<https://github.com/nodejitsu/http-server/blob/master/vendor/node-static/lib/node-static.js#L66>
```

Alternately, modifying the finish function itself (wherever it is) may also work.

**Comment by soluml** [comment]
@cmwelsh realize this is a 6 months later, but :+1:!  Actually was looking at the repo today to see if this was a planned feature. I love this little server, but I can't use it for my SPA's with pushState on for this reason.

**Comment by thecotne** [comment]
any progress on this?

**Comment by jaap3** [comment]
This works unless you use the `-P / --proxy` flag. 

Single page apps can just symlink index.html -> 404.html and everything works. The server will still respond with a 404 code, but that shouldn't matter in most use cases.

**Comment by BigBlueHat** [comment]
The `404.html` file thing has been handled by [node-ecstatic]() for awhile now. I've added a note about it to the `README` https://github.com/indexzero/http-server/commit/9571d0a84913eb2514d68a9c9600742a0791be83 to close this issue.

Thanks, all!
