### ISSUE TITLE
Error: 3316:error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number:openssl\ssl\s3_pkt.c:337:

### ISSUE THREAD

**Issue by Rajaskr** [indexzero/http-server#75]
When i uploading some files through http i got the below error.
Error: 3316:error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number:openssl\ssl\s3_pkt.c:337:
Please let me know why this issue occurred and how to resolve?

**Comment by indexzero** [comment]
I believe this is a problem with your `openssl` installation. It is not a problem with `http-server`. I know it's a little late now, but opening up a question on StackOverflow is a great place to start!
