### ISSUE TITLE
Warnings and the server doesn't start

### ISSUE THREAD

**Issue by SciutoAlex** [indexzero/http-server#78]
I'm not sure what's going on. I tried reinstalling http-server, but it still isn't working. When I run http-server, it says 

<pre>Starting up http-server, serving ./ on port: 8080
Hit CTRL-C to stop the server</pre>

But if I go to http://localhost:8080/, I get a "No Data Received" error in Chrome.

When I installed and reinstalled http-server, I got this error.
![screen shot 2014-05-11 at 8 54 31 pm](https://cloud.githubusercontent.com/assets/1485679/2940255/dbb73da2-d978-11e3-9005-a00fc00f316d.png)

**Comment by indexzero** [comment]
Can you confirm and reopen if it isn't working? Seems to be working as of `0.7.5`.
