### ISSUE TITLE
Server Side Includes Support

### ISSUE THREAD

**Issue by kainy** [indexzero/http-server#83]
Heyo , will http-server support SSI in the future, look forward to it thanks。

**Comment by ryanscherler** [comment]
Any updates on this? It would be great to have this!

**Comment by derhuerst** [comment]
I think this is far beyond the scope of this piece of software. [Server Side Includes](https://en.wikipedia.org/wiki/Server_Side_Includes) are, as far as I know, quite complex and would require quite a bit of restructuring inside.

The purpose of this package is to really just serve static content over HTTP and everything (closely) related to it: directory listings, [CORS](https://de.wikipedia.org/wiki/Cross-Origin_Resource_Sharing) and, a little less closely related, HTTPS.

I'm afraid that this is a feature that won't be used by the majority of the users but will significantly increase the complexity of this project's code. **To me, it seems like a classical case of [feature creep](https://en.wikipedia.org/wiki/Feature_creep) and more suitable to higher-complexity middleware like [*express*](http://expressjs.com/), [*Koa*](http://koajs.com/) or [*hapi*](http://hapijs.com/).**

**Comment by BigBlueHat** [comment]
Yeah...SSI is out of scope for this simple static server project. Cheers!
