### ISSUE TITLE
Version 0.7.1 and 0.7.0 is not working on Windows 7 64

### ISSUE THREAD

**Issue by felquis** [indexzero/http-server#94]
I always recommend http-server for designers etc... it's very easy to use on any folder.

But a friend on Windows 7 64bits can't use it and I don't know why, the server start fine (but using https on 0.7.0 and http in 0.7.1) but we can't navigate in the browser, the browser just show that the page can't be loaded.

I don't know if there's some debug file in somewhere in windows, if it exist I can check it out and share here for debug.

I downgraded to version 0.6.1 and everything worked fine!

**Comment by indexzero** [comment]
Hard to say for certain. Can you have them try again with `http-server@0.8.0`
