### ISSUE TITLE
npm update -g "broke" http-server

### ISSUE THREAD

**Issue by kalanbates** [indexzero/http-server#98]
http-server previously installed globally.  Accidentally issued an npm update to all of global (tacked on -g out of  habit..was typing too fast) and when http-server updated to 0.7.1, it will not start

attempting to run [http-server]
Error: listen EACCES
    at errnoExeption (net.js:904:11)
    at Server._listen2 (net.js:1023:19)
    at listen (net.js:1064:10)
    at net.js:1146:9
    at dns.js:72:18
    at process._tickCallback (node.js:419:13)
    at Function.Module.runMain (module.js:499:11)
    at startup (node.js:119:16)
    at node.js:906:3

**Comment by indexzero** [comment]
Thanks. Closing this then :smile:

**Comment by kalanbates** [comment]
wait. You didn't do anything to address this issue

**Comment by indexzero** [comment]
Nothing changed. I thought the comment from @bleggett solved this issue. 

... can you open an issue on `node-portfinder`? thanks!
